# @name getCloudRegions
GET {{BASE_URL}}/api/v1/cloudRegions
Authorization: Bearer {{ACCESS_TOKEN}}

?? status == 200
###
# @name getOneCloudRegion
# @ref getCloudRegions
GET {{BASE_URL}}/api/v1/cloudRegions/{{ getCloudRegions.data[0].uid }}
Authorization: Bearer {{ACCESS_TOKEN}}

?? status == 200