# @name getAllAccounts
GET {{BASE_URL}}/api/v1/accounts
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

?? status == 200

{{ 
  $global.allAccounts=response.parsedBody.data;
}}
###
# @name filterWorkspaceByName
GET {{BASE_URL}}/api/v1/workspaces?name=default
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}
X-Account-UID: {{$global.allAccounts[0].uid}}

?? status == 200
# Expect only 1 default account per user
?? js response.parsedBody.data.length == 1
{{
  $global.workspace=response.parsedBody.data[0]
}}
###
# @name deleteClusterByUid
DELETE {{BASE_URL}}/api/v1/workspaces/{{ $global.workspace.uid}}/clusters/{{ ACTIVE_CLUSTER_UID }}
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}
?? status == 200