services:
  postgres:
    image: postgres:16
    container_name: sparqd-cp-postgres
    environment:
      POSTGRES_DB: sparqd
      POSTGRES_USER: sparqd
      POSTGRES_PASSWORD: sparqd
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  keycloak-db:
    image: postgres:16
    container_name: sparqd-cp-keycloak-postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak_pgdata:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: sparqd-cp-keycloak
    command: start-dev
    depends_on:
      - keycloak-db
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "${KEYCLOAK_PORT:-8080}:8080"
      - "9000:9000"
    env_file:
      - .env

  redis:
    image: redis:7
    container_name: sparqd-cp-redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    env_file:
      - .env

volumes:
  pgdata:
  keycloak_pgdata:
