import ReactDOM from "react-dom"
import { Button } from "@components/commons"
import { IconAlertTriangle } from "@tabler/icons-react"
import styles from "./UserDelete.module.scss"
import { useUserManagement } from "@context/user/UserContext"

const UserDelete = () => {
  const { closeDeleteModal, deletingUser, handleDeleteUser } =
    useUserManagement()

  if (!deletingUser) return null

  const onConfirmDelete = () => {
    handleDeleteUser(deletingUser.id)
  }

  return ReactDOM.createPortal(
    <div className={styles.overlay}>
      <div className={styles.modal}>
        <div className={styles.header}>
          <IconAlertTriangle size={24} className="text-red-500" />
          <h2 className={styles.title}>Confirm delete</h2>
        </div>
        <div className={styles.content}>
          <p className="text-sm text-gray-600">
            Are you sure you want to delete this user? The user will lose access
            to all workspaces in this account, and:
          </p>
          <ul className="list-disc pl-5 mt-2 space-y-1 text-sm text-gray-500">
            <li>
              Applications or scripts that use the tokens generated by this user
              will no longer be able to access the Databricks API
            </li>
            <li>Jobs configured to run as this user will fail.</li>
            <li>Clusters owned by this user will stop</li>
          </ul>
          <p className="text-sm text-gray-600 mt-4">
            This action cannot be undone.
          </p>
        </div>
        <div className={styles.footer}>
          <Button label="Cancel" variant="outline" onClick={closeDeleteModal} />
          <Button
            label="Confirm delete"
            variant="solid"
            color="danger"
            onClick={onConfirmDelete}
          />
        </div>
      </div>
    </div>,
    document.body,
  )
}

export default UserDelete
