export interface WorkflowData {
  id: number
  enabled: boolean
  name: string
  tag: string
  schedule: string
  lastRun: string
  statusCirclesLeft: {
    status: "empty" | "success" | "error"
    point: number | null
  }[]
  statusCirclesRight: {
    status: "empty" | "success" | "error"
    point: number | null
  }[]
}

export const dataWorkflows: WorkflowData[] = [
  {
    id: 1,
    enabled: true,
    name: "Name of the Workflow",
    tag: "Test",
    schedule: "*/30****",
    lastRun: "Mar 17, 2025 at 10:50 PM",
    statusCirclesLeft: [
      {
        status: "empty",
        point: null,
      },
      {
        status: "success",
        point: 994,
      },
      {
        status: "error",
        point: 994,
      },
    ],
    statusCirclesRight: [
      {
        status: "empty",
        point: null,
      },
      {
        status: "success",
        point: 994,
      },
      {
        status: "success",
        point: 994,
      },
      {
        status: "error",
        point: 994,
      },
      {
        status: "error",
        point: 994,
      },
      {
        status: "error",
        point: 994,
      },
      {
        status: "error",
        point: 994,
      },
      {
        status: "error",
        point: 994,
      },
    ],
  },
  {
    id: 2,
    enabled: true,
    name: "Name of the Workflow",
    tag: "Test",
    schedule: "*/30****",
    lastRun: "Mar 17, 2025 at 10:50 PM",
    statusCirclesLeft: [
      {
        status: "empty",
        point: null,
      },
      {
        status: "success",
        point: 994,
      },
      {
        status: "error",
        point: 994,
      },
    ],
    statusCirclesRight: [
      {
        status: "empty",
        point: null,
      },
      {
        status: "success",
        point: 994,
      },
      {
        status: "success",
        point: 994,
      },
      {
        status: "error",
        point: 994,
      },
      {
        status: "error",
        point: 994,
      },
      {
        status: "error",
        point: 994,
      },
      {
        status: "error",
        point: 994,
      },
      {
        status: "error",
        point: 994,
      },
    ],
  },
  {
    id: 3,
    enabled: true,
    name: "Name of the Workflow",
    tag: "Test",
    schedule: "*/30****",
    lastRun: "Mar 17, 2025 at 10:50 PM",
    statusCirclesLeft: [
      {
        status: "empty",
        point: null,
      },
      {
        status: "success",
        point: 994,
      },
      {
        status: "error",
        point: 994,
      },
    ],
    statusCirclesRight: [
      {
        status: "empty",
        point: null,
      },
      {
        status: "success",
        point: 994,
      },
      {
        status: "success",
        point: 994,
      },
      {
        status: "error",
        point: 994,
      },
      {
        status: "error",
        point: 994,
      },
      {
        status: "error",
        point: 994,
      },
      {
        status: "error",
        point: 994,
      },
      {
        status: "error",
        point: 994,
      },
    ],
  },
  {
    id: 4,
    enabled: true,
    name: "Name of the Workflow",
    tag: "Test",
    schedule: "*/30****",
    lastRun: "Mar 17, 2025 at 10:50 PM",
    statusCirclesLeft: [
      {
        status: "empty",
        point: null,
      },
      {
        status: "success",
        point: 994,
      },
      {
        status: "error",
        point: 994,
      },
    ],
    statusCirclesRight: [
      {
        status: "empty",
        point: null,
      },
      {
        status: "success",
        point: 994,
      },
      {
        status: "success",
        point: 994,
      },
      {
        status: "error",
        point: 994,
      },
      {
        status: "error",
        point: 994,
      },
      {
        status: "error",
        point: 994,
      },
      {
        status: "error",
        point: 994,
      },
      {
        status: "error",
        point: 994,
      },
    ],
  },
]

export const dataWorkflowsApi = {
  dags: [
    {
      dag_display_name: "bronze_parcel",
      dag_id: "bronze_parcel",
      default_view: "grid",
      description: null,
      file_token:
        "Ii9vcHQvYWlyZmxvdy9kYWdzL3JlcG8vZGFncy9icm96bmUtcGFyY2VsLnB5Ig.nRCGP--zvtDIvRt4rffZYUrBJ7k",
      fileloc: "/opt/airflow/dags/repo/dags/brozne-parcel.py",
      has_import_errors: false,
      has_task_concurrency_limits: false,
      is_active: true,
      is_paused: true,
      is_subdag: false,
      last_expired: null,
      last_parsed_time: "2025-05-27T18:18:58.097809+00:00",
      last_pickled: null,
      max_active_runs: 16,
      max_active_tasks: 16,
      max_consecutive_failed_dag_runs: 0,
      next_dagrun: null,
      next_dagrun_create_after: null,
      next_dagrun_data_interval_end: null,
      next_dagrun_data_interval_start: null,
      owners: ["Quant-Data"],
      pickle_id: null,
      root_dag_id: null,
      schedule_interval: null,
      scheduler_lock: null,
      runs_queued: 64,
      runs_success: 32,
      runs_running: 5,
      runs_failed: 6,

      recent_task_none: 0,
      recent_task_removed: 0,
      recent_task_scheduled: 0,
      recent_task_queued: 0,
      recent_task_running: 0,
      recent_task_success: 0,
      recent_task_restarting: 0,
      recent_task_failed: 0,
      recent_task_up_for_retry: 0,
      recent_task_up_for_reschedule: 0,
      recent_task_upstream_failed: 0,
      recent_task_skipped: 0,
      recent_task_deferred: 0,
      recent_task_shutdown: 0,
      last_run: "	Mar 17, 2025 at 10:50 PM",
      schedule: "*/30****",
      tags: [
        {
          name: "spark",
        },
        {
          name: "eks",
        },
        {
          name: "kubernetes",
        },
        {
          name: "papermill",
        },
      ],
      timetable_description: "Never, external triggers only",
    },
    {
      dag_display_name: "bronze_precal_dag",
      dag_id: "bronze_precal_dag",
      default_view: "grid",
      description: null,
      file_token:
        "Ii9vcHQvYWlyZmxvdy9kYWdzL3JlcG8vZGFncy9icm9uemVfcHJlY2FsX2RhZy5weSI.poATCra0Lr_7-ohuAMuhPj1Dhls",
      fileloc: "/opt/airflow/dags/repo/dags/bronze_precal_dag.py",
      has_import_errors: false,
      has_task_concurrency_limits: false,
      is_active: true,
      is_paused: false,
      is_subdag: false,
      last_expired: null,
      last_parsed_time: "2025-05-27T18:18:42.100840+00:00",
      last_pickled: null,
      max_active_runs: 16,
      max_active_tasks: 16,
      max_consecutive_failed_dag_runs: 0,
      next_dagrun: null,
      next_dagrun_create_after: null,
      next_dagrun_data_interval_end: null,
      next_dagrun_data_interval_start: null,
      owners: ["migration-team"],
      pickle_id: null,
      root_dag_id: null,
      schedule_interval: null,
      scheduler_lock: null,
      runs_queued: 64,
      runs_success: 32,
      runs_running: 5,
      runs_failed: 6,
      recent_task_none: 0,
      recent_task_removed: 0,
      recent_task_scheduled: 0,
      recent_task_queued: 0,
      recent_task_running: 0,
      recent_task_success: 0,
      recent_task_restarting: 0,
      recent_task_failed: 0,
      recent_task_up_for_retry: 0,
      recent_task_up_for_reschedule: 0,
      recent_task_upstream_failed: 0,
      recent_task_skipped: 0,
      recent_task_deferred: 0,
      last_run: "	Mar 17, 2025 at 10:50 PM",
      recent_task_shutdown: 0,
      schedule: "*/30****",
      tags: [
        {
          name: "migration",
        },
        {
          name: "bronze",
        },
      ],
      timetable_description: "Never, external triggers only",
    },
    {
      dag_display_name: "bronze-precal-job",
      dag_id: "bronze-precal-job",
      default_view: "grid",
      description: null,
      file_token:
        ".eJxT0s8vKNFPzCxKy8kv109JTC_WL0otyIewkory86pSQex4CDO-oCg1OTFHr6BSCQBiZxVh.THKZlZl5pWozxU3IIHjef_Bivfo",
      fileloc: "/opt/airflow/dags/repo/dags/bronze/dag_bronze_precal.py",
      has_import_errors: false,
      has_task_concurrency_limits: false,
      is_active: true,
      is_paused: false,
      is_subdag: false,
      last_expired: null,
      last_parsed_time: "2025-05-27T18:19:03.301176+00:00",
      last_pickled: null,
      max_active_runs: 16,
      max_active_tasks: 16,
      max_consecutive_failed_dag_runs: 0,
      next_dagrun: null,
      next_dagrun_create_after: null,
      next_dagrun_data_interval_end: null,
      next_dagrun_data_interval_start: null,
      owners: ["airflow"],
      pickle_id: null,
      root_dag_id: null,
      schedule_interval: null,
      scheduler_lock: null,
      runs_queued: 64,
      runs_success: 32,
      runs_running: 5,
      runs_failed: 6,
      recent_task_none: 0,
      recent_task_removed: 0,
      recent_task_scheduled: 0,
      recent_task_queued: 0,
      recent_task_running: 0,
      recent_task_success: 0,
      recent_task_restarting: 0,
      recent_task_failed: 0,
      recent_task_up_for_retry: 0,
      recent_task_up_for_reschedule: 0,
      recent_task_upstream_failed: 0,
      recent_task_skipped: 0,
      recent_task_deferred: 0,
      last_run: "	Mar 17, 2025 at 10:50 PM",
      recent_task_shutdown: 0,
      schedule: "*/30****",
      tags: [
        {
          name: "kubernetes",
        },
        {
          name: "spark-operator",
        },
        {
          name: "example",
        },
        {
          name: "spark",
        },
      ],
      timetable_description: "Never, external triggers only",
    },
    {
      dag_display_name: "example_bash_operator",
      dag_id: "example_bash_operator",
      default_view: "grid",
      description: null,
      file_token:
        "Ii9vcHQvYWlyZmxvdy9kYWdzL3JlcG8vZGFncy9leGFtcGxlX2Jhc2hfb3BlcmF0b3IucHki.EfOSwIQ83WKvi8f6HNwd-ubHi0s",
      fileloc: "/opt/airflow/dags/repo/dags/example_bash_operator.py",
      has_import_errors: false,
      has_task_concurrency_limits: false,
      is_active: true,
      is_paused: true,
      is_subdag: false,
      last_expired: null,
      last_parsed_time: "2025-05-06T07:50:46.706320+00:00",
      last_pickled: null,
      max_active_runs: 16,
      max_active_tasks: 16,
      max_consecutive_failed_dag_runs: 0,
      next_dagrun: "2025-05-05T00:00:00+00:00",
      next_dagrun_create_after: "2025-05-06T00:00:00+00:00",
      next_dagrun_data_interval_end: "2025-05-06T00:00:00+00:00",
      next_dagrun_data_interval_start: "2025-05-05T00:00:00+00:00",
      owners: ["airflow"],
      pickle_id: null,
      root_dag_id: null,
      schedule_interval: {
        __type: "CronExpression",
        value: "0 0 * * *",
      },
      scheduler_lock: null,
      runs_queued: 64,
      runs_success: 32,
      runs_running: 5,
      runs_failed: 6,
      recent_task_none: 0,
      recent_task_removed: 0,
      recent_task_scheduled: 0,
      recent_task_queued: 0,
      recent_task_running: 0,
      recent_task_success: 0,
      recent_task_restarting: 0,
      recent_task_failed: 0,
      recent_task_up_for_retry: 0,
      recent_task_up_for_reschedule: 0,
      recent_task_upstream_failed: 0,
      recent_task_skipped: 0,
      recent_task_deferred: 0,
      last_run: "	Mar 17, 2025 at 10:50 PM",
      recent_task_shutdown: 0,
      schedule: "*/30****",
      tags: [
        {
          name: "example2",
        },
        {
          name: "example",
        },
      ],
      timetable_description: "At 00:00",
    },
    {
      dag_display_name: "example_pyspark_pi_job",
      dag_id: "example_pyspark_pi_job",
      default_view: "grid",
      description: "submit spark-pi as sparkApplication on kubernetes",
      file_token:
        "Ii9vcHQvYWlyZmxvdy9kYWdzL3JlcG8vZGFncy9leGFtcGxlX3B5c3BhcmtfcGlfam9iLnB5Ig.71ONKVYyWq_7BYIlknbR4P990_k",
      fileloc: "/opt/airflow/dags/repo/dags/example_pyspark_pi_job.py",
      has_import_errors: false,
      has_task_concurrency_limits: false,
      is_active: true,
      is_paused: true,
      is_subdag: false,
      last_expired: null,
      last_parsed_time: "2025-05-06T07:50:46.714960+00:00",
      last_pickled: null,
      max_active_runs: 16,
      max_active_tasks: 16,
      max_consecutive_failed_dag_runs: 0,
      next_dagrun: "2025-05-06T00:00:00+00:00",
      next_dagrun_create_after: "2025-05-07T00:00:00+00:00",
      next_dagrun_data_interval_end: "2025-05-07T00:00:00+00:00",
      next_dagrun_data_interval_start: "2025-05-06T00:00:00+00:00",
      owners: ["airflow"],
      pickle_id: null,
      root_dag_id: null,
      schedule_interval: {
        __type: "TimeDelta",
        days: 1,
        microseconds: 0,
        seconds: 0,
      },
      scheduler_lock: null,
      runs_queued: 64,
      runs_success: 32,
      runs_running: 5,
      runs_failed: 6,
      recent_task_none: 0,
      recent_task_removed: 0,
      recent_task_scheduled: 0,
      recent_task_queued: 0,
      recent_task_running: 0,
      recent_task_success: 0,
      recent_task_restarting: 0,
      recent_task_failed: 0,
      recent_task_up_for_retry: 0,
      recent_task_up_for_reschedule: 0,
      recent_task_upstream_failed: 0,
      recent_task_skipped: 0,
      recent_task_deferred: 0,
      last_run: "	Mar 17, 2025 at 10:50 PM",
      recent_task_shutdown: 0,
      schedule: "*/30****",
      tags: [],
      timetable_description: "",
    },
    {
      dag_display_name: "example_spark_operator",
      dag_id: "example_spark_operator",
      default_view: "grid",
      description: null,
      file_token:
        "Ii9vcHQvYWlyZmxvdy9kYWdzL3JlcG8vZGFncy9zYW1wbGUtZGFnLnB5Ig.HJ-DueQs9lX8SvHv_iXqFNP9jsA",
      fileloc: "/opt/airflow/dags/repo/dags/sample-dag.py",
      has_import_errors: false,
      has_task_concurrency_limits: false,
      is_active: true,
      is_paused: true,
      is_subdag: false,
      last_expired: null,
      last_parsed_time: "2025-05-27T18:18:54.614828+00:00",
      last_pickled: null,
      max_active_runs: 16,
      max_active_tasks: 16,
      max_consecutive_failed_dag_runs: 0,
      next_dagrun: null,
      next_dagrun_create_after: null,
      next_dagrun_data_interval_end: null,
      next_dagrun_data_interval_start: null,
      owners: ["quant-data"],
      pickle_id: null,
      root_dag_id: null,
      schedule_interval: null,
      scheduler_lock: null,
      runs_queued: 64,
      runs_success: 32,
      runs_running: 5,
      runs_failed: 6,
      recent_task_none: 0,
      recent_task_removed: 0,
      recent_task_scheduled: 0,
      recent_task_queued: 0,
      recent_task_running: 0,
      recent_task_success: 0,
      recent_task_restarting: 0,
      recent_task_failed: 0,
      recent_task_up_for_retry: 0,
      recent_task_up_for_reschedule: 0,
      recent_task_upstream_failed: 0,
      recent_task_skipped: 0,
      recent_task_deferred: 0,
      last_run: "	Mar 17, 2025 at 10:50 PM",
      recent_task_shutdown: 0,
      schedule: "*/30****",
      tags: [
        {
          name: "example",
        },
      ],
      timetable_description: "Never, external triggers only",
    },
    {
      dag_display_name: "hello_world_scheduled_dag",
      dag_id: "hello_world_scheduled_dag",
      default_view: "grid",
      description: "Scheduled Apache Airflow DAG",
      file_token:
        ".eJxT0s8vKNFPzCxKy8kv109JTC_WL0otyIewoMLxQE58akVibkFOql5BpRIA-8UTew.Lw9RKeWlTDgVbx_2_FinN2J6Jdw",
      fileloc: "/opt/airflow/dags/repo/dags/airflow_dag_example.py",
      has_import_errors: false,
      has_task_concurrency_limits: false,
      is_active: true,
      is_paused: true,
      is_subdag: false,
      last_expired: null,
      last_parsed_time: "2025-05-06T07:50:47.658909+00:00",
      last_pickled: null,
      max_active_runs: 16,
      max_active_tasks: 16,
      max_consecutive_failed_dag_runs: 0,
      next_dagrun: "2025-05-06T01:58:00+00:00",
      next_dagrun_create_after: "2025-05-06T01:59:00+00:00",
      next_dagrun_data_interval_end: "2025-05-06T01:59:00+00:00",
      next_dagrun_data_interval_start: "2025-05-06T01:58:00+00:00",
      owners: ["airflow"],
      pickle_id: null,
      root_dag_id: null,
      schedule_interval: {
        __type: "CronExpression",
        value: "* 1 * * *",
      },
      scheduler_lock: null,
      runs_queued: 64,
      runs_success: 32,
      runs_running: 5,
      runs_failed: 6,
      recent_task_none: 0,
      recent_task_removed: 0,
      recent_task_scheduled: 0,
      recent_task_queued: 0,
      recent_task_running: 0,
      recent_task_success: 0,
      recent_task_restarting: 0,
      recent_task_failed: 0,
      recent_task_up_for_retry: 0,
      recent_task_up_for_reschedule: 0,
      recent_task_upstream_failed: 0,
      recent_task_skipped: 0,
      recent_task_deferred: 0,
      last_run: "	Mar 17, 2025 at 10:50 PM",
      recent_task_shutdown: 0,
      schedule: "*/30****",
      tags: [
        {
          name: "example",
        },
      ],
      timetable_description: "Every minute, between 01:00 and 01:59",
    },
    {
      dag_display_name: "mongo-test",
      dag_id: "mongo-test",
      default_view: "grid",
      description: null,
      file_token:
        "Ii9vcHQvYWlyZmxvdy9kYWdzL3JlcG8vZGFncy9tb25nby10ZXN0LnB5Ig.mcHQ_m5zyG3bTt4MEGpgKqk6XX4",
      fileloc: "/opt/airflow/dags/repo/dags/mongo-test.py",
      has_import_errors: false,
      has_task_concurrency_limits: false,
      is_active: true,
      is_paused: false,
      is_subdag: false,
      last_expired: null,
      last_parsed_time: "2025-05-27T18:18:57.910722+00:00",
      last_pickled: null,
      max_active_runs: 16,
      max_active_tasks: 16,
      max_consecutive_failed_dag_runs: 0,
      next_dagrun: null,
      next_dagrun_create_after: null,
      next_dagrun_data_interval_end: null,
      next_dagrun_data_interval_start: null,
      owners: ["airflow"],
      pickle_id: null,
      root_dag_id: null,
      schedule_interval: null,
      scheduler_lock: null,
      runs_queued: 64,
      runs_success: 32,
      runs_running: 5,
      runs_failed: 6,
      recent_task_none: 0,
      recent_task_removed: 0,
      recent_task_scheduled: 0,
      recent_task_queued: 0,
      recent_task_running: 0,
      recent_task_success: 0,
      recent_task_restarting: 0,
      recent_task_failed: 0,
      recent_task_up_for_retry: 0,
      recent_task_up_for_reschedule: 0,
      recent_task_upstream_failed: 0,
      recent_task_skipped: 0,
      recent_task_deferred: 0,
      last_run: "	Mar 17, 2025 at 10:50 PM",
      recent_task_shutdown: 0,
      schedule: "*/30****",
      tags: [
        {
          name: "spark",
        },
        {
          name: "eks",
        },
        {
          name: "kubernetes",
        },
        {
          name: "papermill",
        },
      ],
      timetable_description: "Never, external triggers only",
    },
    {
      dag_display_name: "precal-job-all",
      dag_id: "precal-job-all",
      default_view: "grid",
      description: null,
      file_token:
        "Ii9vcHQvYWlyZmxvdy9kYWdzL3JlcG8vZGFncy9mdWxsX2RhdGEvcHJlY2FsX2RhZy5weSI.J15yrDMDitG5D2jNqwz_56ocF1M",
      fileloc: "/opt/airflow/dags/repo/dags/full_data/precal_dag.py",
      has_import_errors: false,
      has_task_concurrency_limits: false,
      is_active: true,
      is_paused: false,
      is_subdag: false,
      last_expired: null,
      last_parsed_time: "2025-05-27T18:19:03.027817+00:00",
      last_pickled: null,
      max_active_runs: 16,
      max_active_tasks: 16,
      max_consecutive_failed_dag_runs: 0,
      next_dagrun: null,
      next_dagrun_create_after: null,
      next_dagrun_data_interval_end: null,
      next_dagrun_data_interval_start: null,
      owners: ["airflow"],
      pickle_id: null,
      root_dag_id: null,
      schedule_interval: null,
      scheduler_lock: null,
      runs_queued: 64,
      runs_success: 32,
      runs_running: 5,
      runs_failed: 6,
      recent_task_none: 0,
      recent_task_removed: 0,
      recent_task_scheduled: 0,
      recent_task_queued: 0,
      recent_task_running: 0,
      recent_task_success: 0,
      recent_task_restarting: 0,
      recent_task_failed: 0,
      recent_task_up_for_retry: 0,
      recent_task_up_for_reschedule: 0,
      recent_task_upstream_failed: 0,
      recent_task_skipped: 0,
      recent_task_deferred: 0,
      last_run: "	Mar 17, 2025 at 10:50 PM",
      recent_task_shutdown: 0,
      schedule: "*/30****",
      tags: [
        {
          name: "kubernetes",
        },
        {
          name: "spark-operator",
        },
        {
          name: "example",
        },
        {
          name: "spark",
        },
      ],
      timetable_description: "Never, external triggers only",
    },
    {
      dag_display_name: "precal-job-all-io-optimized",
      dag_id: "precal-job-all-io-optimized",
      default_view: "grid",
      description: null,
      file_token:
        "Ii9vcHQvYWlyZmxvdy9kYWdzL3JlcG8vZGFncy9mdWxsX2RhdGEvcHJlY2FsX2RhZ19pb19vcHRpbWl6ZWQucHki.WmkFtkPdPv8-Siaw7o_RP6lkwVg",
      fileloc:
        "/opt/airflow/dags/repo/dags/full_data/precal_dag_io_optimized.py",
      has_import_errors: false,
      has_task_concurrency_limits: false,
      is_active: true,
      is_paused: true,
      is_subdag: false,
      last_expired: null,
      last_parsed_time: "2025-05-27T18:19:02.098001+00:00",
      last_pickled: null,
      max_active_runs: 16,
      max_active_tasks: 16,
      max_consecutive_failed_dag_runs: 0,
      next_dagrun: null,
      next_dagrun_create_after: null,
      next_dagrun_data_interval_end: null,
      next_dagrun_data_interval_start: null,
      owners: ["airflow"],
      pickle_id: null,
      root_dag_id: null,
      schedule_interval: null,
      scheduler_lock: null,
      runs_queued: 64,
      runs_success: 32,
      runs_running: 5,
      runs_failed: 6,
      recent_task_none: 0,
      recent_task_removed: 0,
      recent_task_scheduled: 0,
      recent_task_queued: 0,
      recent_task_running: 0,
      recent_task_success: 0,
      recent_task_restarting: 0,
      recent_task_failed: 0,
      recent_task_up_for_retry: 0,
      recent_task_up_for_reschedule: 0,
      recent_task_upstream_failed: 0,
      recent_task_skipped: 0,
      recent_task_deferred: 0,
      last_run: "	Mar 17, 2025 at 10:50 PM",
      recent_task_shutdown: 0,
      schedule: "*/30****",
      tags: [
        {
          name: "kubernetes",
        },
        {
          name: "spark-operator",
        },
        {
          name: "example",
        },
        {
          name: "spark",
        },
      ],
      timetable_description: "Never, external triggers only",
    },
    {
      dag_display_name: "precal-job-all-v1",
      dag_id: "precal-job-all-v1",
      default_view: "grid",
      description: null,
      file_token:
        ".eJxT0s8vKNFPzCxKy8kv109JTC_WL0otyIewEnNyikuKUhNzQaz4gqLU5MSceIhIPFCBXkGlEgAGaRgq.KSsRQkeDWngSDmg917Zgb2NvsRA",
      fileloc: "/opt/airflow/dags/repo/dags/allstream/all_precal_stream_dag.py",
      has_import_errors: false,
      has_task_concurrency_limits: false,
      is_active: true,
      is_paused: true,
      is_subdag: false,
      last_expired: null,
      last_parsed_time: "2025-05-27T18:18:42.057934+00:00",
      last_pickled: null,
      max_active_runs: 16,
      max_active_tasks: 16,
      max_consecutive_failed_dag_runs: 0,
      next_dagrun: null,
      next_dagrun_create_after: null,
      next_dagrun_data_interval_end: null,
      next_dagrun_data_interval_start: null,
      owners: ["airflow"],
      pickle_id: null,
      root_dag_id: null,
      schedule_interval: null,
      scheduler_lock: null,
      runs_queued: 64,
      runs_success: 32,
      runs_running: 5,
      runs_failed: 6,
      recent_task_none: 0,
      recent_task_removed: 0,
      recent_task_scheduled: 0,
      recent_task_queued: 0,
      recent_task_running: 0,
      recent_task_success: 0,
      recent_task_restarting: 0,
      recent_task_failed: 0,
      recent_task_up_for_retry: 0,
      recent_task_up_for_reschedule: 0,
      recent_task_upstream_failed: 0,
      recent_task_skipped: 0,
      recent_task_deferred: 0,
      last_run: "	Mar 17, 2025 at 10:50 PM",
      recent_task_shutdown: 0,
      schedule: "*/30****",
      tags: [
        {
          name: "kubernetes",
        },
        {
          name: "spark-operator",
        },
        {
          name: "example",
        },
        {
          name: "spark",
        },
      ],
      timetable_description: "Never, external triggers only",
    },
    {
      dag_display_name: "precal-job-bronze-stream-v1",
      dag_id: "precal-job-bronze-stream-v1",
      default_view: "grid",
      description: null,
      file_token:
        "Ii9vcHQvYWlyZmxvdy9kYWdzL3JlcG8vZGFncy9hbGxzdHJlYW0vcHJlY2FsX2Jyb256ZV9zdHJlYW0ucHki.6gfYiFheivOb8op394CvwPaNDR0",
      fileloc: "/opt/airflow/dags/repo/dags/allstream/precal_bronze_stream.py",
      has_import_errors: false,
      has_task_concurrency_limits: false,
      is_active: true,
      is_paused: true,
      is_subdag: false,
      last_expired: null,
      last_parsed_time: "2025-05-27T18:19:04.817712+00:00",
      last_pickled: null,
      max_active_runs: 16,
      max_active_tasks: 16,
      max_consecutive_failed_dag_runs: 0,
      next_dagrun: null,
      next_dagrun_create_after: null,
      next_dagrun_data_interval_end: null,
      next_dagrun_data_interval_start: null,
      owners: ["airflow"],
      pickle_id: null,
      root_dag_id: null,
      schedule_interval: null,
      scheduler_lock: null,
      runs_queued: 64,
      runs_success: 32,
      runs_running: 5,
      runs_failed: 6,
      recent_task_none: 0,
      recent_task_removed: 0,
      recent_task_scheduled: 0,
      recent_task_queued: 0,
      recent_task_running: 0,
      recent_task_success: 0,
      recent_task_restarting: 0,
      recent_task_failed: 0,
      recent_task_up_for_retry: 0,
      recent_task_up_for_reschedule: 0,
      recent_task_upstream_failed: 0,
      recent_task_skipped: 0,
      recent_task_deferred: 0,
      last_run: "	Mar 17, 2025 at 10:50 PM",
      recent_task_shutdown: 0,
      schedule: "*/30****",
      tags: [
        {
          name: "kubernetes",
        },
        {
          name: "spark-operator",
        },
        {
          name: "example",
        },
        {
          name: "spark",
        },
      ],
      timetable_description: "Never, external triggers only",
    },
    {
      dag_display_name: "precal-job-raw-stream-v1",
      dag_id: "precal-job-raw-stream-v1",
      default_view: "grid",
      description: null,
      file_token:
        "Ii9vcHQvYWlyZmxvdy9kYWdzL3JlcG8vZGFncy9hbGxzdHJlYW0vcHJlY2FsX3Jhd19zdHJlYW0ucHki.tSbYnvVwGT_qetc6npuDfS-ML38",
      fileloc: "/opt/airflow/dags/repo/dags/allstream/precal_raw_stream.py",
      has_import_errors: false,
      has_task_concurrency_limits: false,
      is_active: true,
      is_paused: false,
      is_subdag: false,
      last_expired: null,
      last_parsed_time: "2025-05-27T18:19:04.312488+00:00",
      last_pickled: null,
      max_active_runs: 16,
      max_active_tasks: 16,
      max_consecutive_failed_dag_runs: 0,
      next_dagrun: null,
      next_dagrun_create_after: null,
      next_dagrun_data_interval_end: null,
      next_dagrun_data_interval_start: null,
      owners: ["airflow"],
      pickle_id: null,
      root_dag_id: null,
      schedule_interval: null,
      scheduler_lock: null,
      runs_queued: 64,
      runs_success: 32,
      runs_running: 5,
      runs_failed: 6,
      recent_task_none: 0,
      recent_task_removed: 0,
      recent_task_scheduled: 0,
      recent_task_queued: 0,
      recent_task_running: 0,
      recent_task_success: 0,
      recent_task_restarting: 0,
      recent_task_failed: 0,
      recent_task_up_for_retry: 0,
      recent_task_up_for_reschedule: 0,
      recent_task_upstream_failed: 0,
      recent_task_skipped: 0,
      recent_task_deferred: 0,
      last_run: "	Mar 17, 2025 at 10:50 PM",
      recent_task_shutdown: 0,
      schedule: "*/30****",
      tags: [
        {
          name: "kubernetes",
        },
        {
          name: "spark-operator",
        },
        {
          name: "example",
        },
        {
          name: "spark",
        },
      ],
      timetable_description: "Never, external triggers only",
    },
    {
      dag_display_name: "precal-job-silver-stream-v1",
      dag_id: "precal-job-silver-stream-v1",
      default_view: "grid",
      description: null,
      file_token:
        "Ii9vcHQvYWlyZmxvdy9kYWdzL3JlcG8vZGFncy9hbGxzdHJlYW0vcHJlY2FsX3NpbHZlcl9zdHJlYW0ucHki.uNkkr6vp24RavDobcQTR_fbeong",
      fileloc: "/opt/airflow/dags/repo/dags/allstream/precal_silver_stream.py",
      has_import_errors: false,
      has_task_concurrency_limits: false,
      is_active: true,
      is_paused: true,
      is_subdag: false,
      last_expired: null,
      last_parsed_time: "2025-05-27T18:19:03.719805+00:00",
      last_pickled: null,
      max_active_runs: 16,
      max_active_tasks: 16,
      max_consecutive_failed_dag_runs: 0,
      next_dagrun: null,
      next_dagrun_create_after: null,
      next_dagrun_data_interval_end: null,
      next_dagrun_data_interval_start: null,
      owners: ["airflow"],
      pickle_id: null,
      root_dag_id: null,
      schedule_interval: null,
      scheduler_lock: null,
      runs_queued: 64,
      runs_success: 32,
      runs_running: 5,
      runs_failed: 6,
      recent_task_none: 0,
      recent_task_removed: 0,
      recent_task_scheduled: 0,
      recent_task_queued: 0,
      recent_task_running: 0,
      recent_task_success: 0,
      recent_task_restarting: 0,
      recent_task_failed: 0,
      recent_task_up_for_retry: 0,
      recent_task_up_for_reschedule: 0,
      recent_task_upstream_failed: 0,
      recent_task_skipped: 0,
      recent_task_deferred: 0,
      last_run: "	Mar 17, 2025 at 10:50 PM",
      recent_task_shutdown: 0,
      schedule: "*/30****",
      tags: [
        {
          name: "kubernetes",
        },
        {
          name: "spark-operator",
        },
        {
          name: "example",
        },
        {
          name: "spark",
        },
      ],
      timetable_description: "Never, external triggers only",
    },
    {
      dag_display_name: "raw_precal_dag",
      dag_id: "raw_precal_dag",
      default_view: "grid",
      description: null,
      file_token:
        "Ii9vcHQvYWlyZmxvdy9kYWdzL3JlcG8vZGFncy9yYXdfcHJlY2FsX2RhZy5weSI.n2a4t02nxpcrG68dURWVLYdxjoE",
      fileloc: "/opt/airflow/dags/repo/dags/raw_precal_dag.py",
      has_import_errors: false,
      has_task_concurrency_limits: false,
      is_active: true,
      is_paused: false,
      is_subdag: false,
      last_expired: null,
      last_parsed_time: "2025-05-27T18:19:00.737386+00:00",
      last_pickled: null,
      max_active_runs: 16,
      max_active_tasks: 16,
      max_consecutive_failed_dag_runs: 0,
      next_dagrun: null,
      next_dagrun_create_after: null,
      next_dagrun_data_interval_end: null,
      next_dagrun_data_interval_start: null,
      owners: ["migration-team"],
      pickle_id: null,
      root_dag_id: null,
      schedule_interval: null,
      scheduler_lock: null,
      runs_queued: 64,
      runs_success: 32,
      runs_running: 5,
      runs_failed: 6,
      recent_task_none: 0,
      recent_task_removed: 0,
      recent_task_scheduled: 0,
      recent_task_queued: 0,
      recent_task_running: 0,
      recent_task_success: 0,
      recent_task_restarting: 0,
      recent_task_failed: 0,
      recent_task_up_for_retry: 0,
      recent_task_up_for_reschedule: 0,
      recent_task_upstream_failed: 0,
      recent_task_skipped: 0,
      recent_task_deferred: 0,
      last_run: "	Mar 17, 2025 at 10:50 PM",
      recent_task_shutdown: 0,
      schedule: "*/30****",
      tags: [
        {
          name: "migration",
        },
        {
          name: "raw",
        },
      ],
      timetable_description: "Never, external triggers only",
    },
    {
      dag_display_name: "raw-precal-example",
      dag_id: "raw-precal-example",
      default_view: "grid",
      description: null,
      file_token:
        ".eJxT0s8vKNFPzCxKy8kv109JTC_WL0otyIeyEsFC8UA6vqAoNTkxR6-gUgkA48oS1Q.1ON9y6YaCJM72D7qPMqgxfzAVhc",
      fileloc: "/opt/airflow/dags/repo/dags/raw/dag_raw_precal.py",
      has_import_errors: false,
      has_task_concurrency_limits: false,
      is_active: true,
      is_paused: false,
      is_subdag: false,
      last_expired: null,
      last_parsed_time: "2025-05-27T18:18:43.796498+00:00",
      last_pickled: null,
      max_active_runs: 16,
      max_active_tasks: 16,
      max_consecutive_failed_dag_runs: 0,
      next_dagrun: null,
      next_dagrun_create_after: null,
      next_dagrun_data_interval_end: null,
      next_dagrun_data_interval_start: null,
      owners: ["airflow"],
      pickle_id: null,
      root_dag_id: null,
      schedule_interval: null,
      scheduler_lock: null,
      runs_queued: 64,
      runs_success: 32,
      runs_running: 5,
      runs_failed: 6,
      recent_task_none: 0,
      recent_task_removed: 0,
      recent_task_scheduled: 0,
      recent_task_queued: 0,
      recent_task_running: 0,
      recent_task_success: 0,
      recent_task_restarting: 0,
      recent_task_failed: 0,
      recent_task_up_for_retry: 0,
      recent_task_up_for_reschedule: 0,
      recent_task_upstream_failed: 0,
      recent_task_skipped: 0,
      recent_task_deferred: 0,
      last_run: "	Mar 17, 2025 at 10:50 PM",
      recent_task_shutdown: 0,
      schedule: "*/30****",
      tags: [
        {
          name: "kubernetes",
        },
        {
          name: "spark-operator",
        },
        {
          name: "example",
        },
        {
          name: "spark",
        },
      ],
      timetable_description: "Never, external triggers only",
    },
    {
      dag_display_name: "run_pyspark_notebook_via_k8s_pod",
      dag_id: "run_pyspark_notebook_via_k8s_pod",
      default_view: "grid",
      description: null,
      file_token:
        "Ii9vcHQvYWlyZmxvdy9kYWdzL3JlcG8vZGFncy9zYW1wbGUtZGFnLXBhcGVybWlsbC5weSI.8beb5T_1Iwkb-6QQ7ywWmKRgQv8",
      fileloc: "/opt/airflow/dags/repo/dags/sample-dag-papermill.py",
      has_import_errors: false,
      has_task_concurrency_limits: false,
      is_active: true,
      is_paused: true,
      is_subdag: false,
      last_expired: null,
      last_parsed_time: "2025-05-27T18:18:54.949101+00:00",
      last_pickled: null,
      max_active_runs: 16,
      max_active_tasks: 16,
      max_consecutive_failed_dag_runs: 0,
      next_dagrun: null,
      next_dagrun_create_after: null,
      next_dagrun_data_interval_end: null,
      next_dagrun_data_interval_start: null,
      owners: ["airflow"],
      pickle_id: null,
      root_dag_id: null,
      schedule_interval: null,
      scheduler_lock: null,
      runs_queued: 64,
      runs_success: 32,
      runs_running: 5,
      runs_failed: 6,
      recent_task_none: 0,
      recent_task_removed: 0,
      recent_task_scheduled: 0,
      recent_task_queued: 0,
      recent_task_running: 0,
      recent_task_success: 0,
      recent_task_restarting: 0,
      recent_task_failed: 0,
      recent_task_up_for_retry: 0,
      recent_task_up_for_reschedule: 0,
      recent_task_upstream_failed: 0,
      recent_task_skipped: 0,
      recent_task_deferred: 0,
      last_run: "	Mar 17, 2025 at 10:50 PM",
      recent_task_shutdown: 0,
      schedule: "*/30****",
      tags: [
        {
          name: "spark",
        },
        {
          name: "eks",
        },
        {
          name: "kubernetes",
        },
        {
          name: "papermill",
        },
      ],
      timetable_description: "Never, external triggers only",
    },
    {
      dag_display_name: "run_spark_notebook_with_papermill",
      dag_id: "run_spark_notebook_with_papermill",
      default_view: "grid",
      description: null,
      file_token:
        "Ii9vcHQvYWlyZmxvdy9kYWdzL3JlcG8vZGFncy9zcGFya19qb2JfdGVzdC5weSI.FFGQIchRK3P3GZROJuW1LnAyiD4",
      fileloc: "/opt/airflow/dags/repo/dags/spark_job_test.py",
      has_import_errors: false,
      has_task_concurrency_limits: false,
      is_active: true,
      is_paused: true,
      is_subdag: false,
      last_expired: null,
      last_parsed_time: "2025-05-27T18:18:43.907498+00:00",
      last_pickled: null,
      max_active_runs: 16,
      max_active_tasks: 16,
      max_consecutive_failed_dag_runs: 0,
      next_dagrun: null,
      next_dagrun_create_after: null,
      next_dagrun_data_interval_end: null,
      next_dagrun_data_interval_start: null,
      owners: ["airflow"],
      pickle_id: null,
      root_dag_id: null,
      schedule_interval: null,
      scheduler_lock: null,
      runs_queued: 64,
      runs_success: 32,
      runs_running: 5,
      runs_failed: 6,
      recent_task_none: 0,
      recent_task_removed: 0,
      recent_task_scheduled: 0,
      recent_task_queued: 0,
      recent_task_running: 0,
      recent_task_success: 0,
      recent_task_restarting: 0,
      recent_task_failed: 0,
      recent_task_up_for_retry: 0,
      recent_task_up_for_reschedule: 0,
      recent_task_upstream_failed: 0,
      recent_task_skipped: 0,
      recent_task_deferred: 0,
      last_run: "	Mar 17, 2025 at 10:50 PM",
      recent_task_shutdown: 0,
      schedule: "*/30****",
      tags: [],
      timetable_description: "Never, external triggers only",
    },
    {
      dag_display_name: "Sample_DAG_Papermill",
      dag_id: "Sample_DAG_Papermill",
      default_view: "grid",
      description: null,
      file_token:
        "Ii9vcHQvYWlyZmxvdy9kYWdzL3JlcG8vZGFncy9zYW1wbGUtZGFnLXNwYXJrLXN1Ym1pdC5weSI.bH6Hp9yhCiKr12bhwpESBFKJbuU",
      fileloc: "/opt/airflow/dags/repo/dags/sample-dag-spark-submit.py",
      has_import_errors: false,
      has_task_concurrency_limits: false,
      is_active: true,
      is_paused: true,
      is_subdag: false,
      last_expired: null,
      last_parsed_time: "2025-05-27T18:19:00.717608+00:00",
      last_pickled: null,
      max_active_runs: 16,
      max_active_tasks: 16,
      max_consecutive_failed_dag_runs: 0,
      next_dagrun: null,
      next_dagrun_create_after: null,
      next_dagrun_data_interval_end: null,
      next_dagrun_data_interval_start: null,
      owners: ["Quant-Data"],
      pickle_id: null,
      root_dag_id: null,
      schedule_interval: null,
      scheduler_lock: null,
      runs_queued: 64,
      runs_success: 32,
      runs_running: 5,
      runs_failed: 6,
      recent_task_none: 0,
      recent_task_removed: 0,
      recent_task_scheduled: 0,
      recent_task_queued: 0,
      recent_task_running: 0,
      recent_task_success: 0,
      recent_task_restarting: 0,
      recent_task_failed: 0,
      recent_task_up_for_retry: 0,
      recent_task_up_for_reschedule: 0,
      recent_task_upstream_failed: 0,
      recent_task_skipped: 0,
      recent_task_deferred: 0,
      last_run: "	Mar 17, 2025 at 10:50 PM",
      recent_task_shutdown: 0,
      schedule: "*/30****",
      tags: [
        {
          name: "spark",
        },
        {
          name: "eks",
        },
        {
          name: "kubernetes",
        },
        {
          name: "papermill",
        },
      ],
      timetable_description: "Never, external triggers only",
    },
    {
      dag_display_name: "sample-dag-papermill2",
      dag_id: "sample-dag-papermill2",
      default_view: "grid",
      description: null,
      file_token:
        "Ii9vcHQvYWlyZmxvdy9kYWdzL3JlcG8vZGFncy9zYW1wbGUtZGFnLXBhcGVybWlsbDIucHki.Lb72kThgAvXI2qxaioiWBHfcdOc",
      fileloc: "/opt/airflow/dags/repo/dags/sample-dag-papermill2.py",
      has_import_errors: false,
      has_task_concurrency_limits: false,
      is_active: true,
      is_paused: true,
      is_subdag: false,
      last_expired: null,
      last_parsed_time: "2025-05-27T18:18:47.131026+00:00",
      last_pickled: null,
      max_active_runs: 16,
      max_active_tasks: 16,
      max_consecutive_failed_dag_runs: 0,
      next_dagrun: null,
      next_dagrun_create_after: null,
      next_dagrun_data_interval_end: null,
      next_dagrun_data_interval_start: null,
      owners: ["Quant-Data"],
      pickle_id: null,
      root_dag_id: null,
      schedule_interval: null,
      scheduler_lock: null,
      runs_queued: 64,
      runs_success: 32,
      runs_running: 5,
      runs_failed: 6,
      recent_task_none: 0,
      recent_task_removed: 0,
      recent_task_scheduled: 0,
      recent_task_queued: 0,
      recent_task_running: 0,
      recent_task_success: 0,
      recent_task_restarting: 0,
      recent_task_failed: 0,
      recent_task_up_for_retry: 0,
      recent_task_up_for_reschedule: 0,
      recent_task_upstream_failed: 0,
      recent_task_skipped: 0,
      recent_task_deferred: 0,
      last_run: "	Mar 17, 2025 at 10:50 PM",
      recent_task_shutdown: 0,
      schedule: "*/30****",
      tags: [
        {
          name: "eks",
        },
        {
          name: "spark",
        },
        {
          name: "kubernetes",
        },
        {
          name: "papermill",
        },
      ],
      timetable_description: "Never, external triggers only",
    },
    {
      dag_display_name: "Sample_DAG_Papermill_3",
      dag_id: "Sample_DAG_Papermill_3",
      default_view: "grid",
      description: null,
      file_token:
        "Ii9vcHQvYWlyZmxvdy9kYWdzL3JlcG8vZGFncy9zYW1wbGUtZGFnLXBhcGVybWlsbDMucHki.QisUZ-TE2EeOYnaoDvNDZAcHbHw",
      fileloc: "/opt/airflow/dags/repo/dags/sample-dag-papermill3.py",
      has_import_errors: false,
      has_task_concurrency_limits: false,
      is_active: true,
      is_paused: true,
      is_subdag: false,
      last_expired: null,
      last_parsed_time: "2025-05-27T18:18:46.759293+00:00",
      last_pickled: null,
      max_active_runs: 16,
      max_active_tasks: 16,
      max_consecutive_failed_dag_runs: 0,
      next_dagrun: null,
      next_dagrun_create_after: null,
      next_dagrun_data_interval_end: null,
      next_dagrun_data_interval_start: null,
      owners: ["Quant-Data"],
      pickle_id: null,
      root_dag_id: null,
      schedule_interval: null,
      scheduler_lock: null,
      runs_queued: 64,
      runs_success: 32,
      runs_running: 5,
      runs_failed: 6,
      recent_task_none: 0,
      recent_task_removed: 0,
      recent_task_scheduled: 0,
      recent_task_queued: 0,
      recent_task_running: 0,
      recent_task_success: 0,
      recent_task_restarting: 0,
      recent_task_failed: 0,
      recent_task_up_for_retry: 0,
      recent_task_up_for_reschedule: 0,
      recent_task_upstream_failed: 0,
      recent_task_skipped: 0,
      recent_task_deferred: 0,
      last_run: "	Mar 17, 2025 at 10:50 PM",
      recent_task_shutdown: 0,
      schedule: "*/30****",
      tags: [
        {
          name: "eks",
        },
        {
          name: "spark",
        },
        {
          name: "kubernetes",
        },
        {
          name: "papermill",
        },
      ],
      timetable_description: "Never, external triggers only",
    },
    {
      dag_display_name: "sample-data-dag",
      dag_id: "sample-data-dag",
      default_view: "grid",
      description: null,
      file_token:
        "Ii9vcHQvYWlyZmxvdy9kYWdzL3JlcG8vZGFncy9kZWx0YXdyaXRlL2RhZ19zYW1wbGVfcHJlY2FsLnB5Ig.fV9T8mSiNmvGJX4xP_YFjlUuVDw",
      fileloc: "/opt/airflow/dags/repo/dags/deltawrite/dag_sample_precal.py",
      has_import_errors: false,
      has_task_concurrency_limits: false,
      is_active: true,
      is_paused: true,
      is_subdag: false,
      last_expired: null,
      last_parsed_time: "2025-05-27T18:18:57.616312+00:00",
      last_pickled: null,
      max_active_runs: 16,
      max_active_tasks: 16,
      max_consecutive_failed_dag_runs: 0,
      next_dagrun: null,
      next_dagrun_create_after: null,
      next_dagrun_data_interval_end: null,
      next_dagrun_data_interval_start: null,
      owners: ["airflow"],
      pickle_id: null,
      root_dag_id: null,
      schedule_interval: null,
      scheduler_lock: null,
      runs_queued: 64,
      runs_success: 32,
      runs_running: 5,
      runs_failed: 6,
      recent_task_none: 0,
      recent_task_removed: 0,
      recent_task_scheduled: 0,
      recent_task_queued: 0,
      recent_task_running: 0,
      recent_task_success: 0,
      recent_task_restarting: 0,
      recent_task_failed: 0,
      recent_task_up_for_retry: 0,
      recent_task_up_for_reschedule: 0,
      recent_task_upstream_failed: 0,
      recent_task_skipped: 0,
      recent_task_deferred: 0,
      last_run: "	Mar 17, 2025 at 10:50 PM",
      recent_task_shutdown: 0,
      schedule: "*/30****",
      tags: [
        {
          name: "kubernetes",
        },
        {
          name: "spark-operator",
        },
        {
          name: "example",
        },
        {
          name: "spark",
        },
      ],
      timetable_description: "Never, external triggers only",
    },
    {
      dag_display_name: "silver_parcel",
      dag_id: "silver_parcel",
      default_view: "grid",
      description: null,
      file_token:
        "Ii9vcHQvYWlyZmxvdy9kYWdzL3JlcG8vZGFncy9zaWx2ZXItcGFyY2VsLnB5Ig.SKkWrPRkyldyxxScr0polt2iS7g",
      fileloc: "/opt/airflow/dags/repo/dags/silver-parcel.py",
      has_import_errors: false,
      has_task_concurrency_limits: false,
      is_active: true,
      is_paused: true,
      is_subdag: false,
      last_expired: null,
      last_parsed_time: "2025-05-27T18:18:54.138532+00:00",
      last_pickled: null,
      max_active_runs: 16,
      max_active_tasks: 16,
      max_consecutive_failed_dag_runs: 0,
      next_dagrun: null,
      next_dagrun_create_after: null,
      next_dagrun_data_interval_end: null,
      next_dagrun_data_interval_start: null,
      owners: ["Quant-Data"],
      pickle_id: null,
      root_dag_id: null,
      schedule_interval: null,
      scheduler_lock: null,
      runs_queued: 64,
      runs_success: 32,
      runs_running: 5,
      runs_failed: 6,
      recent_task_none: 0,
      recent_task_removed: 0,
      recent_task_scheduled: 0,
      recent_task_queued: 0,
      recent_task_running: 0,
      recent_task_success: 0,
      recent_task_restarting: 0,
      recent_task_failed: 0,
      recent_task_up_for_retry: 0,
      recent_task_up_for_reschedule: 0,
      recent_task_upstream_failed: 0,
      recent_task_skipped: 0,
      recent_task_deferred: 0,
      last_run: "	Mar 17, 2025 at 10:50 PM",
      recent_task_shutdown: 0,
      schedule: "*/30****",
      tags: [
        {
          name: "papermill",
        },
        {
          name: "eks",
        },
        {
          name: "kubernetes",
        },
        {
          name: "spark",
        },
      ],
      timetable_description: "Never, external triggers only",
    },
    {
      dag_display_name: "silver_parcel_test_night",
      dag_id: "silver_parcel_test_night",
      default_view: "grid",
      description: null,
      file_token:
        "Ii9vcHQvYWlyZmxvdy9kYWdzL3JlcG8vZGFncy9zaWx2ZXItcGFyY2VsX3Rlc3RfbmlnaHQucHki.3qdyhnGJf8QnVVMiPhRIxjO56Mg",
      fileloc: "/opt/airflow/dags/repo/dags/silver-parcel_test_night.py",
      has_import_errors: false,
      has_task_concurrency_limits: false,
      is_active: true,
      is_paused: true,
      is_subdag: false,
      last_expired: null,
      last_parsed_time: "2025-05-27T18:18:51.265721+00:00",
      last_pickled: null,
      max_active_runs: 16,
      max_active_tasks: 16,
      max_consecutive_failed_dag_runs: 0,
      next_dagrun: null,
      next_dagrun_create_after: null,
      next_dagrun_data_interval_end: null,
      next_dagrun_data_interval_start: null,
      owners: ["Quant-Data"],
      pickle_id: null,
      root_dag_id: null,
      schedule_interval: null,
      scheduler_lock: null,
      runs_queued: 64,
      runs_success: 32,
      runs_running: 5,
      runs_failed: 6,
      recent_task_none: 0,
      recent_task_removed: 0,
      recent_task_scheduled: 0,
      recent_task_queued: 0,
      recent_task_running: 0,
      recent_task_success: 0,
      recent_task_restarting: 0,
      recent_task_failed: 0,
      recent_task_up_for_retry: 0,
      recent_task_up_for_reschedule: 0,
      recent_task_upstream_failed: 0,
      recent_task_skipped: 0,
      recent_task_deferred: 0,
      last_run: "	Mar 17, 2025 at 10:50 PM",
      recent_task_shutdown: 0,
      schedule: "*/30****",
      tags: [
        {
          name: "eks",
        },
        {
          name: "spark",
        },
        {
          name: "kubernetes",
        },
        {
          name: "papermill",
        },
      ],
      timetable_description: "Never, external triggers only",
    },
    {
      dag_display_name: "silver_precal_dag",
      dag_id: "silver_precal_dag",
      default_view: "grid",
      description: null,
      file_token:
        "Ii9vcHQvYWlyZmxvdy9kYWdzL3JlcG8vZGFncy9zaWx2ZXJfcHJlY2FsX2RhZy5weSI.W-36biiYdeX-aWdBQfOR3sbWqlk",
      fileloc: "/opt/airflow/dags/repo/dags/silver_precal_dag.py",
      has_import_errors: false,
      has_task_concurrency_limits: false,
      is_active: true,
      is_paused: false,
      is_subdag: false,
      last_expired: null,
      last_parsed_time: "2025-05-27T18:18:54.740759+00:00",
      last_pickled: null,
      max_active_runs: 16,
      max_active_tasks: 16,
      max_consecutive_failed_dag_runs: 0,
      next_dagrun: null,
      next_dagrun_create_after: null,
      next_dagrun_data_interval_end: null,
      next_dagrun_data_interval_start: null,
      owners: ["migration-team"],
      pickle_id: null,
      root_dag_id: null,
      schedule_interval: null,
      scheduler_lock: null,
      runs_queued: 64,
      runs_success: 32,
      runs_running: 5,
      runs_failed: 6,
      recent_task_none: 0,
      recent_task_removed: 0,
      recent_task_scheduled: 0,
      recent_task_queued: 0,
      recent_task_running: 0,
      recent_task_success: 0,
      recent_task_restarting: 0,
      recent_task_failed: 0,
      recent_task_up_for_retry: 0,
      recent_task_up_for_reschedule: 0,
      recent_task_upstream_failed: 0,
      recent_task_skipped: 0,
      recent_task_deferred: 0,
      last_run: "	Mar 17, 2025 at 10:50 PM",
      recent_task_shutdown: 0,
      schedule: "*/30****",
      tags: [
        {
          name: "migration",
        },
        {
          name: "silver",
        },
      ],
      timetable_description: "Never, external triggers only",
    },
    {
      dag_display_name: "silver-precal-example",
      dag_id: "silver-precal-example",
      default_view: "grid",
      description: null,
      file_token:
        ".eJxT0s8vKNFPzCxKy8kv109JTC_WL0otyIewijNzylKLQOx4CDO-oCg1OTFHr6BSCQBjXBVr.x9f9fPhor8gncpYsQp6NPZ-bxpY",
      fileloc: "/opt/airflow/dags/repo/dags/silver/dag_silver_precal.py",
      has_import_errors: false,
      has_task_concurrency_limits: false,
      is_active: true,
      is_paused: true,
      is_subdag: false,
      last_expired: null,
      last_parsed_time: "2025-05-27T18:18:53.797831+00:00",
      last_pickled: null,
      max_active_runs: 16,
      max_active_tasks: 16,
      max_consecutive_failed_dag_runs: 0,
      next_dagrun: null,
      next_dagrun_create_after: null,
      next_dagrun_data_interval_end: null,
      next_dagrun_data_interval_start: null,
      owners: ["airflow"],
      pickle_id: null,
      root_dag_id: null,
      schedule_interval: null,
      scheduler_lock: null,
      runs_queued: 64,
      runs_success: 32,
      runs_running: 5,
      runs_failed: 6,
      recent_task_none: 0,
      recent_task_removed: 0,
      recent_task_scheduled: 0,
      recent_task_queued: 0,
      recent_task_running: 0,
      recent_task_success: 0,
      recent_task_restarting: 0,
      recent_task_failed: 0,
      recent_task_up_for_retry: 0,
      recent_task_up_for_reschedule: 0,
      recent_task_upstream_failed: 0,
      recent_task_skipped: 0,
      recent_task_deferred: 0,
      last_run: "	Mar 17, 2025 at 10:50 PM",
      recent_task_shutdown: 0,
      schedule: "*/30****",
      tags: [
        {
          name: "spark-operator",
        },
        {
          name: "kubernetes",
        },
        {
          name: "spark",
        },
        {
          name: "example",
        },
      ],
      timetable_description: "Never, external triggers only",
    },
    {
      dag_display_name: "silver-precal-fresh",
      dag_id: "silver-precal-fresh",
      default_view: "grid",
      description: null,
      file_token:
        "Ii9vcHQvYWlyZmxvdy9kYWdzL3JlcG8vZGFncy9zaWx2ZXJfcHJlY2FsX2ZyZXNoLnB5Ig.SnvQsRNILi0b8Pz2E2lpX2U5GhM",
      fileloc: "/opt/airflow/dags/repo/dags/silver_precal_fresh.py",
      has_import_errors: false,
      has_task_concurrency_limits: false,
      is_active: true,
      is_paused: true,
      is_subdag: false,
      last_expired: null,
      last_parsed_time: "2025-05-27T18:18:42.397909+00:00",
      last_pickled: null,
      max_active_runs: 16,
      max_active_tasks: 16,
      max_consecutive_failed_dag_runs: 0,
      next_dagrun: null,
      next_dagrun_create_after: null,
      next_dagrun_data_interval_end: null,
      next_dagrun_data_interval_start: null,
      owners: ["airflow"],
      pickle_id: null,
      root_dag_id: null,
      schedule_interval: null,
      scheduler_lock: null,
      runs_queued: 64,
      runs_success: 32,
      runs_running: 5,
      runs_failed: 6,
      recent_task_none: 0,
      recent_task_removed: 0,
      recent_task_scheduled: 0,
      recent_task_queued: 0,
      recent_task_running: 0,
      recent_task_success: 0,
      recent_task_restarting: 0,
      recent_task_failed: 0,
      recent_task_up_for_retry: 0,
      recent_task_up_for_reschedule: 0,
      recent_task_upstream_failed: 0,
      recent_task_skipped: 0,
      recent_task_deferred: 0,
      last_run: "	Mar 17, 2025 at 10:50 PM",
      recent_task_shutdown: 0,
      schedule: "*/30****",
      tags: [
        {
          name: "spark",
        },
        {
          name: "kubernetes",
        },
        {
          name: "spark-operator",
        },
      ],
      timetable_description: "Never, external triggers only",
    },
    {
      dag_display_name: "silver_precal_spark_sb",
      dag_id: "silver_precal_spark_sb",
      default_view: "grid",
      description: null,
      file_token:
        "Ii9vcHQvYWlyZmxvdy9kYWdzL3JlcG8vZGFncy9zaWx2ZXJfcHJlY2FsX3NwYXJrX3MucHki.pjXpNh0-NabTcHFPvo29QvKlGgw",
      fileloc: "/opt/airflow/dags/repo/dags/silver_precal_spark_s.py",
      has_import_errors: false,
      has_task_concurrency_limits: false,
      is_active: true,
      is_paused: true,
      is_subdag: false,
      last_expired: null,
      last_parsed_time: "2025-05-27T18:19:02.668267+00:00",
      last_pickled: null,
      max_active_runs: 16,
      max_active_tasks: 16,
      max_consecutive_failed_dag_runs: 0,
      next_dagrun: null,
      next_dagrun_create_after: null,
      next_dagrun_data_interval_end: null,
      next_dagrun_data_interval_start: null,
      owners: ["Quant-Data"],
      pickle_id: null,
      root_dag_id: null,
      schedule_interval: null,
      scheduler_lock: null,
      runs_queued: 64,
      runs_success: 32,
      runs_running: 5,
      runs_failed: 6,
      recent_task_none: 0,
      recent_task_removed: 0,
      recent_task_scheduled: 0,
      recent_task_queued: 0,
      recent_task_running: 0,
      recent_task_success: 0,
      recent_task_restarting: 0,
      recent_task_failed: 0,
      recent_task_up_for_retry: 0,
      recent_task_up_for_reschedule: 0,
      recent_task_upstream_failed: 0,
      recent_task_skipped: 0,
      recent_task_deferred: 0,
      last_run: "	Mar 17, 2025 at 10:50 PM",
      recent_task_shutdown: 0,
      schedule: "*/30****",
      tags: [
        {
          name: "eks",
        },
        {
          name: "spark",
        },
        {
          name: "kubernetes",
        },
        {
          name: "papermill",
        },
      ],
      timetable_description: "Never, external triggers only",
    },
    {
      dag_display_name: "spark_delta",
      dag_id: "spark_delta",
      default_view: "grid",
      description: null,
      file_token:
        "Ii9vcHQvYWlyZmxvdy9kYWdzL3JlcG8vZGFncy9zYW1wbGUtZGFnLXBhcGVybWlsbC1kZWx0YS5weSI.4xRZh-zOCOQYHBi4K4EjwamcFdE",
      fileloc: "/opt/airflow/dags/repo/dags/sample-dag-papermill-delta.py",
      has_import_errors: false,
      has_task_concurrency_limits: false,
      is_active: true,
      is_paused: true,
      is_subdag: false,
      last_expired: null,
      last_parsed_time: "2025-05-27T18:18:56.122931+00:00",
      last_pickled: null,
      max_active_runs: 16,
      max_active_tasks: 16,
      max_consecutive_failed_dag_runs: 0,
      next_dagrun: null,
      next_dagrun_create_after: null,
      next_dagrun_data_interval_end: null,
      next_dagrun_data_interval_start: null,
      owners: ["airflow"],
      pickle_id: null,
      root_dag_id: null,
      schedule_interval: null,
      scheduler_lock: null,
      runs_queued: 64,
      runs_success: 32,
      runs_running: 5,
      runs_failed: 6,
      recent_task_none: 0,
      recent_task_removed: 0,
      recent_task_scheduled: 0,
      recent_task_queued: 0,
      recent_task_running: 0,
      recent_task_success: 0,
      recent_task_restarting: 0,
      recent_task_failed: 0,
      recent_task_up_for_retry: 0,
      recent_task_up_for_reschedule: 0,
      recent_task_upstream_failed: 0,
      recent_task_skipped: 0,
      recent_task_deferred: 0,
      last_run: "	Mar 17, 2025 at 10:50 PM",
      recent_task_shutdown: 0,
      schedule: "*/30****",
      tags: [
        {
          name: "spark",
        },
        {
          name: "eks",
        },
        {
          name: "kubernetes",
        },
        {
          name: "papermill",
        },
      ],
      timetable_description: "Never, external triggers only",
    },
    {
      dag_display_name: "spark-optimize",
      dag_id: "spark-optimize",
      default_view: "grid",
      description: null,
      file_token:
        ".eJxT0s8vKNFPzCxKy8kv109JTC_WL0otyIewgFKZuZlVqfpFieXxMI5eQaUSACZ8FGs.pU3AapNMknetkT1EdHWxDQzHdCw",
      fileloc: "/opt/airflow/dags/repo/dags/optimize/raw_optimize.py",
      has_import_errors: false,
      has_task_concurrency_limits: false,
      is_active: true,
      is_paused: false,
      is_subdag: false,
      last_expired: null,
      last_parsed_time: "2025-05-27T18:19:01.907977+00:00",
      last_pickled: null,
      max_active_runs: 16,
      max_active_tasks: 16,
      max_consecutive_failed_dag_runs: 0,
      next_dagrun: null,
      next_dagrun_create_after: null,
      next_dagrun_data_interval_end: null,
      next_dagrun_data_interval_start: null,
      owners: ["airflow"],
      pickle_id: null,
      root_dag_id: null,
      schedule_interval: null,
      scheduler_lock: null,
      runs_queued: 64,
      runs_success: 32,
      runs_running: 5,
      runs_failed: 6,
      recent_task_none: 0,
      recent_task_removed: 0,
      recent_task_scheduled: 0,
      recent_task_queued: 0,
      recent_task_running: 0,
      recent_task_success: 0,
      recent_task_restarting: 0,
      recent_task_failed: 0,
      recent_task_up_for_retry: 0,
      recent_task_up_for_reschedule: 0,
      recent_task_upstream_failed: 0,
      recent_task_skipped: 0,
      recent_task_deferred: 0,
      last_run: "	Mar 17, 2025 at 10:50 PM",
      recent_task_shutdown: 0,
      schedule: "*/30****",
      tags: [
        {
          name: "kubernetes",
        },
        {
          name: "spark-operator",
        },
        {
          name: "example",
        },
        {
          name: "spark",
        },
      ],
      timetable_description: "Never, external triggers only",
    },
    {
      dag_display_name: "spark-optimize-bronze-silver",
      dag_id: "spark-optimize-bronze-silver",
      default_view: "grid",
      description: null,
      file_token:
        ".eJxT0s8vKNFPzCxKy8kv109JTC_WL0otyIewgFKZuZlVqfpJRfl5VanxxZk5ZalF8TBhvYJKJQAOWRil.HmDJ67FMBjqavapJliCK39jgQFc",
      fileloc: "/opt/airflow/dags/repo/dags/optimize/bronze_silver_optimize.py",
      has_import_errors: false,
      has_task_concurrency_limits: false,
      is_active: true,
      is_paused: false,
      is_subdag: false,
      last_expired: null,
      last_parsed_time: "2025-05-27T18:18:52.416550+00:00",
      last_pickled: null,
      max_active_runs: 16,
      max_active_tasks: 16,
      max_consecutive_failed_dag_runs: 0,
      next_dagrun: null,
      next_dagrun_create_after: null,
      next_dagrun_data_interval_end: null,
      next_dagrun_data_interval_start: null,
      owners: ["airflow"],
      pickle_id: null,
      root_dag_id: null,
      schedule_interval: null,
      scheduler_lock: null,
      runs_queued: 64,
      runs_success: 32,
      runs_running: 5,
      runs_failed: 6,
      recent_task_none: 0,
      recent_task_removed: 0,
      recent_task_scheduled: 0,
      recent_task_queued: 0,
      recent_task_running: 0,
      recent_task_success: 0,
      recent_task_restarting: 0,
      recent_task_failed: 0,
      recent_task_up_for_retry: 0,
      recent_task_up_for_reschedule: 0,
      recent_task_upstream_failed: 0,
      recent_task_skipped: 0,
      recent_task_deferred: 0,
      last_run: "	Mar 17, 2025 at 10:50 PM",
      recent_task_shutdown: 0,
      schedule: "*/30****",
      tags: [
        {
          name: "kubernetes",
        },
        {
          name: "spark-operator",
        },
        {
          name: "example",
        },
        {
          name: "spark",
        },
      ],
      timetable_description: "Never, external triggers only",
    },
    {
      dag_display_name: "spark-optimize-create_workflow",
      dag_id: "spark-optimize-create_workflow",
      default_view: "grid",
      description: null,
      file_token:
        "Ii9vcHQvYWlyZmxvdy9kYWdzL3JlcG8vZGFncy9zcGFya19vcHRpX2NyZWF0ZV93b3JrZmxvdy5weSI.500tlIhQOW_vt-V5hEmt0yuOaz4",
      fileloc: "/opt/airflow/dags/repo/dags/spark_opti_create_workflow.py",
      has_import_errors: false,
      has_task_concurrency_limits: false,
      is_active: true,
      is_paused: true,
      is_subdag: false,
      last_expired: null,
      last_parsed_time: "2025-05-27T18:18:45.297974+00:00",
      last_pickled: null,
      max_active_runs: 16,
      max_active_tasks: 16,
      max_consecutive_failed_dag_runs: 0,
      next_dagrun: null,
      next_dagrun_create_after: null,
      next_dagrun_data_interval_end: null,
      next_dagrun_data_interval_start: null,
      owners: ["airflow"],
      pickle_id: null,
      root_dag_id: null,
      schedule_interval: null,
      scheduler_lock: null,
      runs_queued: 64,
      runs_success: 32,
      runs_running: 5,
      runs_failed: 6,
      recent_task_none: 0,
      recent_task_removed: 0,
      recent_task_scheduled: 0,
      recent_task_queued: 0,
      recent_task_running: 0,
      recent_task_success: 0,
      recent_task_restarting: 0,
      recent_task_failed: 0,
      recent_task_up_for_retry: 0,
      recent_task_up_for_reschedule: 0,
      recent_task_upstream_failed: 0,
      recent_task_skipped: 0,
      recent_task_deferred: 0,
      last_run: "	Mar 17, 2025 at 10:50 PM",
      recent_task_shutdown: 0,
      schedule: "*/30****",
      tags: [
        {
          name: "kubernetes",
        },
        {
          name: "spark",
        },
      ],
      timetable_description: "Never, external triggers only",
    },
    {
      dag_display_name: "spark-task-bronze-liquid-cluster",
      dag_id: "spark-task-bronze-liquid-cluster",
      default_view: "grid",
      description: null,
      file_token:
        "Ii9vcHQvYWlyZmxvdy9kYWdzL3JlcG8vZGFncy9vcHRpbWl6ZS9icm9uemVfbGlxdWlkX2NsdXN0ZXJpbmcucHki.MqT9rB03NeuyWj5Sjcgo1WIcUKE",
      fileloc:
        "/opt/airflow/dags/repo/dags/optimize/bronze_liquid_clustering.py",
      has_import_errors: false,
      has_task_concurrency_limits: false,
      is_active: true,
      is_paused: true,
      is_subdag: false,
      last_expired: null,
      last_parsed_time: "2025-05-27T18:18:56.235613+00:00",
      last_pickled: null,
      max_active_runs: 16,
      max_active_tasks: 16,
      max_consecutive_failed_dag_runs: 0,
      next_dagrun: null,
      next_dagrun_create_after: null,
      next_dagrun_data_interval_end: null,
      next_dagrun_data_interval_start: null,
      owners: ["airflow"],
      pickle_id: null,
      root_dag_id: null,
      schedule_interval: null,
      scheduler_lock: null,
      runs_queued: 64,
      runs_success: 32,
      runs_running: 5,
      runs_failed: 6,
      recent_task_none: 0,
      recent_task_removed: 0,
      recent_task_scheduled: 0,
      recent_task_queued: 0,
      recent_task_running: 0,
      recent_task_success: 0,
      recent_task_restarting: 0,
      recent_task_failed: 0,
      recent_task_up_for_retry: 0,
      recent_task_up_for_reschedule: 0,
      recent_task_upstream_failed: 0,
      recent_task_skipped: 0,
      recent_task_deferred: 0,
      last_run: "	Mar 17, 2025 at 10:50 PM",
      recent_task_shutdown: 0,
      schedule: "*/30****",
      tags: [
        {
          name: "kubernetes",
        },
        {
          name: "spark-operator",
        },
        {
          name: "example",
        },
        {
          name: "spark",
        },
      ],
      timetable_description: "Never, external triggers only",
    },
    {
      dag_display_name: "spark-task-raw-liquid-cluster",
      dag_id: "spark-task-raw-liquid-cluster",
      default_view: "grid",
      description: null,
      file_token:
        "Ii9vcHQvYWlyZmxvdy9kYWdzL3JlcG8vZGFncy9vcHRpbWl6ZS9yYXdfbGlxdWlkX2NsdXN0ZXJpbmcucHki.IOgX_v9n3jGVBmBcmvDYbc0PKgY",
      fileloc: "/opt/airflow/dags/repo/dags/optimize/raw_liquid_clustering.py",
      has_import_errors: false,
      has_task_concurrency_limits: false,
      is_active: true,
      is_paused: true,
      is_subdag: false,
      last_expired: null,
      last_parsed_time: "2025-05-27T18:18:45.298066+00:00",
      last_pickled: null,
      max_active_runs: 16,
      max_active_tasks: 16,
      max_consecutive_failed_dag_runs: 0,
      next_dagrun: null,
      next_dagrun_create_after: null,
      next_dagrun_data_interval_end: null,
      next_dagrun_data_interval_start: null,
      owners: ["airflow"],
      pickle_id: null,
      root_dag_id: null,
      schedule_interval: null,
      scheduler_lock: null,
      runs_queued: 64,
      runs_success: 32,
      runs_running: 5,
      runs_failed: 6,
      recent_task_none: 0,
      recent_task_removed: 0,
      recent_task_scheduled: 0,
      recent_task_queued: 0,
      recent_task_running: 0,
      recent_task_success: 0,
      recent_task_restarting: 0,
      recent_task_failed: 0,
      recent_task_up_for_retry: 0,
      recent_task_up_for_reschedule: 0,
      recent_task_upstream_failed: 0,
      recent_task_skipped: 0,
      recent_task_deferred: 0,
      last_run: "	Mar 17, 2025 at 10:50 PM",
      recent_task_shutdown: 0,
      schedule: "*/30****",
      tags: [
        {
          name: "kubernetes",
        },
        {
          name: "spark-operator",
        },
        {
          name: "example",
        },
        {
          name: "spark",
        },
      ],
      timetable_description: "Never, external triggers only",
    },
    {
      dag_display_name: "spark-task-silver-liquid-cluster",
      dag_id: "spark-task-silver-liquid-cluster",
      default_view: "grid",
      description: null,
      file_token:
        "Ii9vcHQvYWlyZmxvdy9kYWdzL3JlcG8vZGFncy9vcHRpbWl6ZS9zaWx2ZXJfbGlxdWlkX2NsdXN0ZXJpbmcucHki.OpLECppTOVay0stKUlMqM0fGIlU",
      fileloc:
        "/opt/airflow/dags/repo/dags/optimize/silver_liquid_clustering.py",
      has_import_errors: false,
      has_task_concurrency_limits: false,
      is_active: true,
      is_paused: true,
      is_subdag: false,
      last_expired: null,
      last_parsed_time: "2025-05-27T18:19:01.101911+00:00",
      last_pickled: null,
      max_active_runs: 16,
      max_active_tasks: 16,
      max_consecutive_failed_dag_runs: 0,
      next_dagrun: null,
      next_dagrun_create_after: null,
      next_dagrun_data_interval_end: null,
      next_dagrun_data_interval_start: null,
      owners: ["airflow"],
      pickle_id: null,
      root_dag_id: null,
      schedule_interval: null,
      scheduler_lock: null,
      runs_queued: 64,
      runs_success: 32,
      runs_running: 5,
      runs_failed: 6,
      recent_task_none: 0,
      recent_task_removed: 0,
      recent_task_scheduled: 0,
      recent_task_queued: 0,
      recent_task_running: 0,
      recent_task_success: 0,
      recent_task_restarting: 0,
      recent_task_failed: 0,
      recent_task_up_for_retry: 0,
      recent_task_up_for_reschedule: 0,
      recent_task_upstream_failed: 0,
      recent_task_skipped: 0,
      recent_task_deferred: 0,
      last_run: "	Mar 17, 2025 at 10:50 PM",
      recent_task_shutdown: 0,
      schedule: "*/30****",
      tags: [
        {
          name: "kubernetes",
        },
        {
          name: "spark-operator",
        },
        {
          name: "example",
        },
        {
          name: "spark",
        },
      ],
      timetable_description: "Never, external triggers only",
    },
    {
      dag_display_name: "test_run_notebook_dag",
      dag_id: "test_run_notebook_dag",
      default_view: "grid",
      description: null,
      file_token:
        "Ii9vcHQvYWlyZmxvdy9kYWdzL3JlcG8vZGFncy90ZXN0cnVuX3MzX2RhZy5weSI.wHSXYbndvrxV3tLwDrD2bPIyx3U",
      fileloc: "/opt/airflow/dags/repo/dags/testrun_s3_dag.py",
      has_import_errors: false,
      has_task_concurrency_limits: false,
      is_active: true,
      is_paused: true,
      is_subdag: false,
      last_expired: null,
      last_parsed_time: "2025-05-27T18:18:51.080726+00:00",
      last_pickled: null,
      max_active_runs: 16,
      max_active_tasks: 16,
      max_consecutive_failed_dag_runs: 0,
      next_dagrun: null,
      next_dagrun_create_after: null,
      next_dagrun_data_interval_end: null,
      next_dagrun_data_interval_start: null,
      owners: ["Quant-Data"],
      pickle_id: null,
      root_dag_id: null,
      schedule_interval: null,
      scheduler_lock: null,
      runs_queued: 64,
      runs_success: 32,
      runs_running: 5,
      runs_failed: 6,
      recent_task_none: 0,
      recent_task_removed: 0,
      recent_task_scheduled: 0,
      recent_task_queued: 0,
      recent_task_running: 0,
      recent_task_success: 0,
      recent_task_restarting: 0,
      recent_task_failed: 0,
      recent_task_up_for_retry: 0,
      recent_task_up_for_reschedule: 0,
      recent_task_upstream_failed: 0,
      recent_task_skipped: 0,
      recent_task_deferred: 0,
      last_run: "	Mar 17, 2025 at 10:50 PM",
      recent_task_shutdown: 0,
      schedule: "*/30****",
      tags: [
        {
          name: "notebook",
        },
        {
          name: "s3",
        },
        {
          name: "kubernetes",
        },
        {
          name: "papermill",
        },
      ],
      timetable_description: "Never, external triggers only",
    },
    {
      dag_display_name: "test_run_notebook_new_dag",
      dag_id: "test_run_notebook_new_dag",
      default_view: "grid",
      description: null,
      file_token:
        "Ii9vcHQvYWlyZmxvdy9kYWdzL3JlcG8vZGFncy90ZXN0X25ld19kYWcucHki.Vfwgnf1sRfcE1fbQYQ7YZM5j-B4",
      fileloc: "/opt/airflow/dags/repo/dags/test_new_dag.py",
      has_import_errors: false,
      has_task_concurrency_limits: false,
      is_active: true,
      is_paused: true,
      is_subdag: false,
      last_expired: null,
      last_parsed_time: "2025-05-27T18:18:53.952774+00:00",
      last_pickled: null,
      max_active_runs: 16,
      max_active_tasks: 16,
      max_consecutive_failed_dag_runs: 0,
      next_dagrun: null,
      next_dagrun_create_after: null,
      next_dagrun_data_interval_end: null,
      next_dagrun_data_interval_start: null,
      owners: ["Quant-Data"],
      pickle_id: null,
      root_dag_id: null,
      schedule_interval: null,
      scheduler_lock: null,
      runs_queued: 64,
      runs_success: 32,
      runs_running: 5,
      runs_failed: 6,
      recent_task_none: 0,
      recent_task_removed: 0,
      recent_task_scheduled: 0,
      recent_task_queued: 0,
      recent_task_running: 0,
      recent_task_success: 0,
      recent_task_restarting: 0,
      recent_task_failed: 0,
      recent_task_up_for_retry: 0,
      recent_task_up_for_reschedule: 0,
      recent_task_upstream_failed: 0,
      recent_task_skipped: 0,
      recent_task_deferred: 0,
      last_run: "	Mar 17, 2025 at 10:50 PM",
      recent_task_shutdown: 0,
      schedule: "*/30****",
      tags: [
        {
          name: "notebook",
        },
        {
          name: "s3",
        },
        {
          name: "kubernetes",
        },
        {
          name: "papermill",
        },
      ],
      timetable_description: "Never, external triggers only",
    },
    {
      dag_display_name: "v2-bronze-stream",
      dag_id: "v2-bronze-stream",
      default_view: "grid",
      description: null,
      file_token:
        "Ii9vcHQvYWlyZmxvdy9kYWdzL3JlcG8vZGFncy9hbGxzdHJlYW0vcHJlY2FsX2Jyb256ZV9zdHJlYW1fYXV0by5weSI.-C3kOdZnIlbnabuDQsnueSkC72g",
      fileloc:
        "/opt/airflow/dags/repo/dags/allstream/precal_bronze_stream_auto.py",
      has_import_errors: false,
      has_task_concurrency_limits: false,
      is_active: true,
      is_paused: false,
      is_subdag: false,
      last_expired: null,
      last_parsed_time: "2025-05-27T18:19:04.798041+00:00",
      last_pickled: null,
      max_active_runs: 16,
      max_active_tasks: 16,
      max_consecutive_failed_dag_runs: 0,
      next_dagrun: null,
      next_dagrun_create_after: null,
      next_dagrun_data_interval_end: null,
      next_dagrun_data_interval_start: null,
      owners: ["airflow"],
      pickle_id: null,
      root_dag_id: null,
      schedule_interval: null,
      scheduler_lock: null,
      runs_queued: 64,
      runs_success: 32,
      runs_running: 5,
      runs_failed: 6,
      recent_task_none: 0,
      recent_task_removed: 0,
      recent_task_scheduled: 0,
      recent_task_queued: 0,
      recent_task_running: 0,
      recent_task_success: 0,
      recent_task_restarting: 0,
      recent_task_failed: 0,
      recent_task_up_for_retry: 0,
      recent_task_up_for_reschedule: 0,
      recent_task_upstream_failed: 0,
      recent_task_skipped: 0,
      recent_task_deferred: 0,
      last_run: "	Mar 17, 2025 at 10:50 PM",
      recent_task_shutdown: 0,
      schedule: "*/30****",
      tags: [
        {
          name: "kubernetes",
        },
        {
          name: "spark-operator",
        },
        {
          name: "example",
        },
        {
          name: "spark",
        },
      ],
      timetable_description: "Never, external triggers only",
    },
    {
      dag_display_name: "V2-dag",
      dag_id: "V2-dag",
      default_view: "grid",
      description: null,
      file_token:
        "Ii9vcHQvYWlyZmxvdy9kYWdzL3JlcG8vZGFncy9WMi1kYWcucHki.JPsPjCX9Y3fP7roSHJAKGDf2-3I",
      fileloc: "/opt/airflow/dags/repo/dags/V2-dag.py",
      has_import_errors: false,
      has_task_concurrency_limits: false,
      is_active: true,
      is_paused: true,
      is_subdag: false,
      last_expired: null,
      last_parsed_time: "2025-05-27T18:18:45.775941+00:00",
      last_pickled: null,
      max_active_runs: 16,
      max_active_tasks: 16,
      max_consecutive_failed_dag_runs: 0,
      next_dagrun: null,
      next_dagrun_create_after: null,
      next_dagrun_data_interval_end: null,
      next_dagrun_data_interval_start: null,
      owners: ["airflow"],
      pickle_id: null,
      root_dag_id: null,
      schedule_interval: null,
      scheduler_lock: null,
      runs_queued: 64,
      runs_success: 32,
      runs_running: 5,
      runs_failed: 6,
      recent_task_none: 0,
      recent_task_removed: 0,
      recent_task_scheduled: 0,
      recent_task_queued: 0,
      recent_task_running: 0,
      recent_task_success: 0,
      recent_task_restarting: 0,
      recent_task_failed: 0,
      recent_task_up_for_retry: 0,
      recent_task_up_for_reschedule: 0,
      recent_task_upstream_failed: 0,
      recent_task_skipped: 0,
      recent_task_deferred: 0,
      last_run: "	Mar 17, 2025 at 10:50 PM",
      recent_task_shutdown: 0,
      schedule: "*/30****",
      tags: [
        {
          name: "spark",
        },
        {
          name: "eks",
        },
        {
          name: "kubernetes",
        },
        {
          name: "papermill",
        },
      ],
      timetable_description: "Never, external triggers only",
    },
    {
      dag_display_name: "V2-dag-bronze",
      dag_id: "V2-dag-bronze",
      default_view: "grid",
      description: null,
      file_token:
        "Ii9vcHQvYWlyZmxvdy9kYWdzL3JlcG8vZGFncy9WMi1kYWctYnJvbnplLnB5Ig.X57bYE9sCCcgf0MWrvKXLGXL6Js",
      fileloc: "/opt/airflow/dags/repo/dags/V2-dag-bronze.py",
      has_import_errors: false,
      has_task_concurrency_limits: false,
      is_active: true,
      is_paused: true,
      is_subdag: false,
      last_expired: null,
      last_parsed_time: "2025-05-27T18:19:02.478773+00:00",
      last_pickled: null,
      max_active_runs: 16,
      max_active_tasks: 16,
      max_consecutive_failed_dag_runs: 0,
      next_dagrun: null,
      next_dagrun_create_after: null,
      next_dagrun_data_interval_end: null,
      next_dagrun_data_interval_start: null,
      owners: ["airflow"],
      pickle_id: null,
      root_dag_id: null,
      schedule_interval: null,
      scheduler_lock: null,
      runs_queued: 64,
      runs_success: 32,
      runs_running: 5,
      runs_failed: 6,
      recent_task_none: 0,
      recent_task_removed: 0,
      recent_task_scheduled: 0,
      recent_task_queued: 0,
      recent_task_running: 0,
      recent_task_success: 0,
      recent_task_restarting: 0,
      recent_task_failed: 0,
      recent_task_up_for_retry: 0,
      recent_task_up_for_reschedule: 0,
      recent_task_upstream_failed: 0,
      recent_task_skipped: 0,
      recent_task_deferred: 0,
      last_run: "	Mar 17, 2025 at 10:50 PM",
      recent_task_shutdown: 0,
      schedule: "*/30****",
      tags: [
        {
          name: "papermill",
        },
        {
          name: "eks",
        },
        {
          name: "kubernetes",
        },
        {
          name: "spark",
        },
      ],
      timetable_description: "Never, external triggers only",
    },
    {
      dag_display_name: "V2-dag-raw",
      dag_id: "V2-dag-raw",
      default_view: "grid",
      description: null,
      file_token:
        "Ii9vcHQvYWlyZmxvdy9kYWdzL3JlcG8vZGFncy9WMi1kYWctcmF3LnB5Ig.EsjksP27-g94ynzyVjv555bA14g",
      fileloc: "/opt/airflow/dags/repo/dags/V2-dag-raw.py",
      has_import_errors: false,
      has_task_concurrency_limits: false,
      is_active: true,
      is_paused: false,
      is_subdag: false,
      last_expired: null,
      last_parsed_time: "2025-05-27T18:18:50.598420+00:00",
      last_pickled: null,
      max_active_runs: 16,
      max_active_tasks: 16,
      max_consecutive_failed_dag_runs: 0,
      next_dagrun: null,
      next_dagrun_create_after: null,
      next_dagrun_data_interval_end: null,
      next_dagrun_data_interval_start: null,
      owners: ["airflow"],
      pickle_id: null,
      root_dag_id: null,
      schedule_interval: null,
      scheduler_lock: null,
      runs_queued: 64,
      runs_success: 32,
      runs_running: 5,
      runs_failed: 6,
      recent_task_none: 0,
      recent_task_removed: 0,
      recent_task_scheduled: 0,
      recent_task_queued: 0,
      recent_task_running: 0,
      recent_task_success: 0,
      recent_task_restarting: 0,
      recent_task_failed: 0,
      recent_task_up_for_retry: 0,
      recent_task_up_for_reschedule: 0,
      recent_task_upstream_failed: 0,
      recent_task_skipped: 0,
      recent_task_deferred: 0,
      last_run: "	Mar 17, 2025 at 10:50 PM",
      recent_task_shutdown: 0,
      schedule: "*/30****",
      tags: [
        {
          name: "papermill",
        },
        {
          name: "eks",
        },
        {
          name: "kubernetes",
        },
        {
          name: "spark",
        },
      ],
      timetable_description: "Never, external triggers only",
    },
    {
      dag_display_name: "V2-dag-silver",
      dag_id: "V2-dag-silver",
      default_view: "grid",
      description: null,
      file_token:
        "Ii9vcHQvYWlyZmxvdy9kYWdzL3JlcG8vZGFncy9WMi1kYWctc2lsdmVyLnB5Ig.Sh2zXQQEvnqsGPfvb7HGNnUTfeU",
      fileloc: "/opt/airflow/dags/repo/dags/V2-dag-silver.py",
      has_import_errors: false,
      has_task_concurrency_limits: false,
      is_active: true,
      is_paused: true,
      is_subdag: false,
      last_expired: null,
      last_parsed_time: "2025-05-27T18:18:50.608497+00:00",
      last_pickled: null,
      max_active_runs: 16,
      max_active_tasks: 16,
      max_consecutive_failed_dag_runs: 0,
      next_dagrun: null,
      next_dagrun_create_after: null,
      next_dagrun_data_interval_end: null,
      next_dagrun_data_interval_start: null,
      owners: ["airflow"],
      pickle_id: null,
      root_dag_id: null,
      schedule_interval: null,
      scheduler_lock: null,
      runs_queued: 64,
      runs_success: 32,
      runs_running: 5,
      runs_failed: 6,
      recent_task_none: 0,
      recent_task_removed: 0,
      recent_task_scheduled: 0,
      recent_task_queued: 0,
      recent_task_running: 0,
      recent_task_success: 0,
      recent_task_restarting: 0,
      recent_task_failed: 0,
      recent_task_up_for_retry: 0,
      recent_task_up_for_reschedule: 0,
      recent_task_upstream_failed: 0,
      recent_task_skipped: 0,
      recent_task_deferred: 0,
      last_run: "	Mar 17, 2025 at 10:50 PM",
      recent_task_shutdown: 0,
      schedule: "*/30****",
      tags: [
        {
          name: "papermill",
        },
        {
          name: "eks",
        },
        {
          name: "kubernetes",
        },
        {
          name: "spark",
        },
      ],
      timetable_description: "Never, external triggers only",
    },
    {
      dag_display_name: "v2-raw-stream",
      dag_id: "v2-raw-stream",
      default_view: "grid",
      description: null,
      file_token:
        "Ii9vcHQvYWlyZmxvdy9kYWdzL3JlcG8vZGFncy9hbGxzdHJlYW0vcHJlY2FsX3Jhd19zdHJlYW1fYXV0by5weSI._-xl_8QGTs71CSpd2mOgOcYXoeI",
      fileloc:
        "/opt/airflow/dags/repo/dags/allstream/precal_raw_stream_auto.py",
      has_import_errors: false,
      has_task_concurrency_limits: false,
      is_active: true,
      is_paused: false,
      is_subdag: false,
      last_expired: null,
      last_parsed_time: "2025-05-27T18:19:04.070917+00:00",
      last_pickled: null,
      max_active_runs: 16,
      max_active_tasks: 16,
      max_consecutive_failed_dag_runs: 0,
      next_dagrun: null,
      next_dagrun_create_after: null,
      next_dagrun_data_interval_end: null,
      next_dagrun_data_interval_start: null,
      owners: ["airflow"],
      pickle_id: null,
      root_dag_id: null,
      schedule_interval: null,
      scheduler_lock: null,
      runs_queued: 64,
      runs_success: 32,
      runs_running: 5,
      runs_failed: 6,
      recent_task_none: 0,
      recent_task_removed: 0,
      recent_task_scheduled: 0,
      recent_task_queued: 0,
      recent_task_running: 0,
      recent_task_success: 0,
      recent_task_restarting: 0,
      recent_task_failed: 0,
      recent_task_up_for_retry: 0,
      recent_task_up_for_reschedule: 0,
      recent_task_upstream_failed: 0,
      recent_task_skipped: 0,
      recent_task_deferred: 0,
      last_run: "	Mar 17, 2025 at 10:50 PM",
      recent_task_shutdown: 0,
      schedule: "*/30****",
      tags: [
        {
          name: "kubernetes",
        },
        {
          name: "spark-operator",
        },
        {
          name: "example",
        },
        {
          name: "spark",
        },
      ],
      timetable_description: "Never, external triggers only",
    },
    {
      dag_display_name: "v2-silver-stream",
      dag_id: "v2-silver-stream",
      default_view: "grid",
      description: null,
      file_token:
        ".eJwlyNEJwDAIBcBdMkAdSR6tDQGLoqah2_cjf8c1Mi_CiFtt0YWeFOK2BdWsEDzkISeUc-grwTsZs-zwr_1woxoT.ln63vG2Au0UNHZW4dhlwKvT9dmg",
      fileloc:
        "/opt/airflow/dags/repo/dags/allstream/precal_silver_stream_auto.py",
      has_import_errors: false,
      has_task_concurrency_limits: false,
      is_active: true,
      is_paused: false,
      is_subdag: false,
      last_expired: null,
      last_parsed_time: "2025-05-27T18:19:03.697835+00:00",
      last_pickled: null,
      max_active_runs: 16,
      max_active_tasks: 16,
      max_consecutive_failed_dag_runs: 0,
      next_dagrun: null,
      next_dagrun_create_after: null,
      next_dagrun_data_interval_end: null,
      next_dagrun_data_interval_start: null,
      owners: ["airflow"],
      pickle_id: null,
      root_dag_id: null,
      schedule_interval: null,
      scheduler_lock: null,
      runs_queued: 64,
      runs_success: 32,
      runs_running: 5,
      runs_failed: 6,
      recent_task_none: 0,
      recent_task_removed: 0,
      recent_task_scheduled: 0,
      recent_task_queued: 0,
      recent_task_running: 0,
      recent_task_success: 0,
      recent_task_restarting: 0,
      recent_task_failed: 0,
      recent_task_up_for_retry: 0,
      recent_task_up_for_reschedule: 0,
      recent_task_upstream_failed: 0,
      recent_task_skipped: 0,
      recent_task_deferred: 0,
      last_run: "	Mar 17, 2025 at 10:50 PM",
      recent_task_shutdown: 0,
      schedule: "*/30****",
      tags: [
        {
          name: "kubernetes",
        },
        {
          name: "spark",
        },
        {
          name: "example",
        },
        {
          name: "spark-operator",
        },
      ],
      timetable_description: "Never, external triggers only",
    },
    {
      dag_display_name: "v2-workflow",
      dag_id: "v2-workflow",
      default_view: "grid",
      description: null,
      file_token:
        "Ii9vcHQvYWlyZmxvdy9kYWdzL3JlcG8vZGFncy9mdWxsX2RhdGEvcHJlY2FsX2pvYl92Mi5weSI.APvkT3cGjDaXeD1wzVX7eYVFx1U",
      fileloc: "/opt/airflow/dags/repo/dags/full_data/precal_job_v2.py",
      has_import_errors: false,
      has_task_concurrency_limits: false,
      is_active: true,
      is_paused: false,
      is_subdag: false,
      last_expired: null,
      last_parsed_time: "2025-05-27T18:19:01.446695+00:00",
      last_pickled: null,
      max_active_runs: 16,
      max_active_tasks: 16,
      max_consecutive_failed_dag_runs: 0,
      next_dagrun: null,
      next_dagrun_create_after: null,
      next_dagrun_data_interval_end: null,
      next_dagrun_data_interval_start: null,
      owners: ["airflow"],
      pickle_id: null,
      root_dag_id: null,
      schedule_interval: null,
      scheduler_lock: null,
      runs_queued: 64,
      runs_success: 32,
      runs_running: 5,
      runs_failed: 6,
      recent_task_none: 0,
      recent_task_removed: 0,
      recent_task_scheduled: 0,
      recent_task_queued: 0,
      recent_task_running: 0,
      recent_task_success: 0,
      recent_task_restarting: 0,
      recent_task_failed: 0,
      recent_task_up_for_retry: 0,
      recent_task_up_for_reschedule: 0,
      recent_task_upstream_failed: 0,
      recent_task_skipped: 0,
      recent_task_deferred: 0,
      last_run: "	Mar 17, 2025 at 10:50 PM",
      recent_task_shutdown: 0,
      schedule: "*/30****",
      tags: [
        {
          name: "kubernetes",
        },
        {
          name: "spark-operator",
        },
        {
          name: "example",
        },
        {
          name: "spark",
        },
      ],
      timetable_description: "Never, external triggers only",
    },
  ],
  total_entries: 45,
}

export const lastDagRuns = {
  CountDistinctGamesByProvider: {
    dag_id: "CountDistinctGamesByProvider",
    data_interval_end: "2025-06-03T02:16:02.041670+00:00",
    data_interval_start: "2025-06-03T02:16:02.041670+00:00",
    end_date: "2025-06-03T02:40:27.047577+00:00",
    execution_date: "2025-06-03T02:16:02.041670+00:00",
    start_date: "2025-06-03T02:16:02.355747+00:00",
    state: "success",
  },
  "bronze-precal-job": {
    dag_id: "bronze-precal-job",
    data_interval_end: "2025-05-16T11:55:16.329965+00:00",
    data_interval_start: "2025-05-16T11:55:16.329965+00:00",
    end_date: "2025-05-16T12:24:08.035818+00:00",
    execution_date: "2025-05-16T11:55:16.329965+00:00",
    start_date: "2025-05-16T11:55:16.633430+00:00",
    state: "success",
  },
  "precal-job-all": {
    dag_id: "precal-job-all",
    data_interval_end: "2025-05-22T05:52:19.008683+00:00",
    data_interval_start: "2025-05-22T05:52:19.008683+00:00",
    end_date: "2025-05-22T07:00:35.336222+00:00",
    execution_date: "2025-05-22T05:52:19.008683+00:00",
    start_date: "2025-05-22T06:51:15.218140+00:00",
    state: "success",
  },
  "precal-job-all-io-optimized": {
    dag_id: "precal-job-all-io-optimized",
    data_interval_end: "2025-05-29T03:58:43.608565+00:00",
    data_interval_start: "2025-05-29T03:58:43.608565+00:00",
    end_date: "2025-05-29T04:53:01.288037+00:00",
    execution_date: "2025-05-29T03:58:43.608565+00:00",
    start_date: "2025-05-29T03:58:44.015275+00:00",
    state: "success",
  },
  "precal-job-all-v1": {
    dag_id: "precal-job-all-v1",
    data_interval_end: "2025-05-18T18:51:05.552412+00:00",
    data_interval_start: "2025-05-18T18:51:05.552412+00:00",
    end_date: "2025-05-18T19:01:43.603441+00:00",
    execution_date: "2025-05-18T18:51:05.552412+00:00",
    start_date: "2025-05-18T18:51:06.441544+00:00",
    state: "success",
  },
  "precal-job-bronze-stream-v1": {
    dag_id: "precal-job-bronze-stream-v1",
    data_interval_end: "2025-05-21T06:47:59.882268+00:00",
    data_interval_start: "2025-05-21T06:47:59.882268+00:00",
    end_date: "2025-05-21T06:50:37.522497+00:00",
    execution_date: "2025-05-21T06:47:59.882268+00:00",
    start_date: "2025-05-21T06:47:59.981730+00:00",
    state: "failed",
  },
  "precal-job-raw-stream-v1": {
    dag_id: "precal-job-raw-stream-v1",
    data_interval_end: "2025-05-20T10:46:20.239050+00:00",
    data_interval_start: "2025-05-20T10:46:20.239050+00:00",
    end_date: "2025-05-20T11:00:00.448088+00:00",
    execution_date: "2025-05-20T10:46:20.239050+00:00",
    start_date: "2025-05-20T10:46:20.429042+00:00",
    state: "success",
  },
  "precal-job-silver-stream-v1": {
    dag_id: "precal-job-silver-stream-v1",
    data_interval_end: "2025-05-19T08:38:25.032384+00:00",
    data_interval_start: "2025-05-19T08:38:25.032384+00:00",
    end_date: "2025-05-19T09:29:15.609770+00:00",
    execution_date: "2025-05-19T08:38:25.032384+00:00",
    start_date: "2025-05-19T08:38:26.041244+00:00",
    state: "failed",
  },
  "raw-precal-example": {
    dag_id: "raw-precal-example",
    data_interval_end: "2025-05-18T09:37:56.145119+00:00",
    data_interval_start: "2025-05-18T09:37:56.145119+00:00",
    end_date: "2025-05-18T09:42:17.313499+00:00",
    execution_date: "2025-05-18T09:37:56.145119+00:00",
    start_date: "2025-05-18T09:37:56.666307+00:00",
    state: "success",
  },
  "sample-data-dag": {
    dag_id: "sample-data-dag",
    data_interval_end: "2025-05-29T08:35:23.060557+00:00",
    data_interval_start: "2025-05-29T08:35:23.060557+00:00",
    end_date: "2025-05-29T08:38:45.002001+00:00",
    execution_date: "2025-05-29T08:35:23.060557+00:00",
    start_date: "2025-05-29T08:35:24.097893+00:00",
    state: "success",
  },
  "silver-precal-example": {
    dag_id: "silver-precal-example",
    data_interval_end: "2025-05-15T16:23:42.431480+00:00",
    data_interval_start: "2025-05-15T16:23:42.431480+00:00",
    end_date: "2025-05-15T20:36:44.523419+00:00",
    execution_date: "2025-05-15T16:23:42.431480+00:00",
    start_date: "2025-05-15T16:23:43.253942+00:00",
    state: "failed",
  },
  "silver-precal-fresh": {
    dag_id: "silver-precal-fresh",
    data_interval_end: "2025-05-15T09:17:42.882311+00:00",
    data_interval_start: "2025-05-15T09:17:42.882311+00:00",
    end_date: "2025-05-15T10:06:04.022907+00:00",
    execution_date: "2025-05-15T09:17:42.882311+00:00",
    start_date: "2025-05-15T09:17:43.890470+00:00",
    state: "success",
  },
  "spark-optimize": {
    dag_id: "spark-optimize",
    data_interval_end: "2025-06-09T15:59:43.904428+00:00",
    data_interval_start: "2025-06-09T15:59:43.904428+00:00",
    end_date: "2025-06-09T16:14:50.053424+00:00",
    execution_date: "2025-06-09T15:59:43.904428+00:00",
    start_date: "2025-06-09T15:59:45.236517+00:00",
    state: "success",
  },
  "spark-optimize-bronze": {
    dag_id: "spark-optimize-bronze",
    data_interval_end: "2025-06-09T15:59:49.270247+00:00",
    data_interval_start: "2025-06-09T15:59:49.270247+00:00",
    end_date: "2025-06-09T17:06:25.180339+00:00",
    execution_date: "2025-06-09T15:59:49.270247+00:00",
    start_date: "2025-06-09T15:59:49.544883+00:00",
    state: "success",
  },
  "spark-optimize-silver": {
    dag_id: "spark-optimize-silver",
    data_interval_end: "2025-06-21T19:58:17.334505+00:00",
    data_interval_start: "2025-06-21T19:58:17.334505+00:00",
    end_date: "2025-06-21T20:31:04.430681+00:00",
    execution_date: "2025-06-21T19:58:17.334505+00:00",
    start_date: "2025-06-21T19:58:18.625193+00:00",
    state: "success",
  },
  "spark-optimize-silver-company": {
    dag_id: "spark-optimize-silver-company",
    data_interval_end: "2025-06-21T20:02:26.376247+00:00",
    data_interval_start: "2025-06-21T20:02:26.376247+00:00",
    end_date: "2025-06-22T00:26:42.809313+00:00",
    execution_date: "2025-06-21T20:02:26.376247+00:00",
    start_date: "2025-06-21T20:04:43.319214+00:00",
    state: "failed",
  },
  "spark-task-bronze-liquid-cluster": {
    dag_id: "spark-task-bronze-liquid-cluster",
    data_interval_end: "2025-05-17T15:21:21.354130+00:00",
    data_interval_start: "2025-05-17T15:21:21.354130+00:00",
    end_date: "2025-05-17T15:24:13.669274+00:00",
    execution_date: "2025-05-17T15:21:21.354130+00:00",
    start_date: "2025-05-17T15:21:22.423073+00:00",
    state: "success",
  },
  "spark-task-raw-liquid-cluster": {
    dag_id: "spark-task-raw-liquid-cluster",
    data_interval_end: "2025-05-17T07:28:09.431784+00:00",
    data_interval_start: "2025-05-17T07:28:09.431784+00:00",
    end_date: "2025-05-17T07:42:46.316086+00:00",
    execution_date: "2025-05-17T07:28:09.431784+00:00",
    start_date: "2025-05-17T07:28:09.741112+00:00",
    state: "success",
  },
  "spark-task-silver-liquid-cluster": {
    dag_id: "spark-task-silver-liquid-cluster",
    data_interval_end: "2025-05-17T15:22:19.261970+00:00",
    data_interval_start: "2025-05-17T15:22:19.261970+00:00",
    end_date: "2025-05-17T15:24:57.756146+00:00",
    execution_date: "2025-05-17T15:22:19.261970+00:00",
    start_date: "2025-05-17T15:22:19.962275+00:00",
    state: "success",
  },
  stream_data_validate: {
    dag_id: "stream_data_validate",
    data_interval_end: "2025-06-24T19:59:49.793266+00:00",
    data_interval_start: "2025-06-24T19:59:49.793266+00:00",
    end_date: "2025-06-24T20:01:23.336670+00:00",
    execution_date: "2025-06-24T19:59:49.793266+00:00",
    start_date: "2025-06-24T19:59:50.492633+00:00",
    state: "failed",
  },
  "v2-bronze-migration": {
    dag_id: "v2-bronze-migration",
    data_interval_end: "2025-06-23T14:00:16.864046+00:00",
    data_interval_start: "2025-06-23T14:00:16.864046+00:00",
    end_date: "2025-06-23T22:45:56.278319+00:00",
    execution_date: "2025-06-23T14:00:16.864046+00:00",
    start_date: "2025-06-23T14:00:17.207477+00:00",
    state: "success",
  },
  "v2-bronze-stream": {
    dag_id: "v2-bronze-stream",
    data_interval_end: "2025-06-15T14:17:41.217463+00:00",
    data_interval_start: "2025-06-15T14:17:41.217463+00:00",
    end_date: "2025-06-18T08:41:21.105916+00:00",
    execution_date: "2025-06-15T14:17:41.217463+00:00",
    start_date: "2025-06-15T14:17:41.376521+00:00",
    state: "failed",
  },
  "v2-raw-migration": {
    dag_id: "v2-raw-migration",
    data_interval_end: "2025-06-23T18:03:55.748422+00:00",
    data_interval_start: "2025-06-23T18:03:55.748422+00:00",
    end_date: "2025-06-23T21:31:36.242567+00:00",
    execution_date: "2025-06-23T18:03:55.748422+00:00",
    start_date: "2025-06-23T18:03:56.200359+00:00",
    state: "success",
  },
  "v2-raw-stream": {
    dag_id: "v2-raw-stream",
    data_interval_end: "2025-06-15T14:24:53.022488+00:00",
    data_interval_start: "2025-06-15T14:24:53.022488+00:00",
    end_date: "2025-06-21T02:00:56.415029+00:00",
    execution_date: "2025-06-15T14:24:53.022488+00:00",
    start_date: "2025-06-15T14:24:54.348898+00:00",
    state: "success",
  },
  "v2-silver-stream": {
    dag_id: "v2-silver-stream",
    data_interval_end: "2025-06-15T18:08:12.835681+00:00",
    data_interval_start: "2025-06-15T18:08:12.835681+00:00",
    end_date: "2025-06-20T00:08:46.516492+00:00",
    execution_date: "2025-06-15T18:08:12.835681+00:00",
    start_date: "2025-06-15T18:08:13.320564+00:00",
    state: "failed",
  },
  "v2-workflow": {
    dag_id: "v2-workflow",
    data_interval_end: "2025-05-20T15:21:24.173977+00:00",
    data_interval_start: "2025-05-20T15:21:24.173977+00:00",
    end_date: "2025-05-20T15:46:57.604692+00:00",
    execution_date: "2025-05-20T15:21:24.173977+00:00",
    start_date: "2025-05-20T15:21:24.432074+00:00",
    state: "success",
  },
}
