# -------------------------------------------------------
# CI Workflow
# - Runs on feature branches (feat/**, fix/**, etc.)
# - Runs on PRs into main
# - Purpose: run tests, lint, build checks
# - Does NOT deploy or push Docker images
# -------------------------------------------------------
name: control-plane-frontend-ci

on:
  workflow_dispatch:
  push:
    branches:
      - feat/**
      - fix/**
      - chore/**
      - refactor/**
      - docs/**
      - test/**
      - ci/**
      - perf/**
      - release/**
      - hotfix/**
    paths:
      - "control-plane-frontend/src/**"
      - ".github/workflows/control-plane-frontend-ci.yml"
  pull_request:
    branches:
      - main
    paths:
      - "control-plane-frontend/src/**"
      - ".github/workflows/control-plane-frontend-ci.yml"

env:
  AWS_REGION: ap-southeast-1                        # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: sparqd/control-plane-frontend     # set this to your Amazon ECR repository name
  ARGO_REPO: sparqd/sparqd-control-plane-argocd

permissions:
  contents: read

jobs:
  test-and-build:
    environment: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: control-plane-frontend

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Run build
        run: pnpm build
        env:
          VITE_AIRFLOW_URL: ${{ vars.VITE_AIRFLOW_URL   }}
          VITE_API_URL: ${{ vars.VITE_API_URL }}
          VITE_AUTH_USERNAME: ${{ vars.VITE_AUTH_USERNAME }}
          VITE_AUTH_PASSWORD: ${{ vars.VITE_AUTH_PASSWORD }}
          VITE_JUPYTER_API_URL: ${{ vars.VITE_JUPYTER_API_URL }}
          VITE_KEYCLOAK_CLIENT_ID: ${{ vars.VITE_KEYCLOAK_CLIENT_ID }}
          VITE_KEYCLOAK_REALM: ${{ vars.VITE_KEYCLOAK_REALM }}
          VITE_KEYCLOAK_URL: ${{ vars.VITE_KEYCLOAK_URL }}
          VITE_CONTROL_PLANE_API_BASE_URL: ${{ vars.VITE_CONTROL_PLANE_API_BASE_URL }}
          VITE_NEW_API: ${{ vars.VITE_NEW_API }}

      # - name: Run tests
      #   run: pnpm test
